/*
 Highcharts 4.0.4 JS v/Highstock 2.0.4 (2014-09-02)

 (c) 2009-2014 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(){function x(a,b){var c;a||(a={});for(c in b)a[c]=b[c];return a}function C(){var a,b=arguments,c,d={},e=function(a,b){var c,d;"object"!==typeof a&&(a={});for(d in b)b.hasOwnProperty(d)&&((c=b[d])&&"object"===typeof c&&"[object Array]"!==Object.prototype.toString.call(c)&&"renderTo"!==d&&"number"!==typeof c.nodeType?a[d]=e(a[d]||{},c):a[d]=b[d]);return a};!0===b[0]&&(d=b[1],b=Array.prototype.slice.call(b,2));c=b.length;for(a=0;a<c;a++)d=e(d,b[a]);return d}function z(a,b){return parseInt(a,
b||10)}function ga(a){return"string"===typeof a}function aa(a){return a&&"object"===typeof a}function xa(a){return"[object Array]"===Object.prototype.toString.call(a)}function ba(a){return"number"===typeof a}function qa(a){return H.log(a)/H.LN10}function ca(a){return H.pow(10,a)}function ha(a,b){for(var c=a.length;c--;)if(a[c]===b){a.splice(c,1);break}}function u(a){return a!==v&&null!==a}function G(a,b,c){var d,e;if(ga(b))u(c)?a.setAttribute(b,c):a&&a.getAttribute&&(e=a.getAttribute(b));else if(u(b)&&
aa(b))for(d in b)a.setAttribute(d,b[d]);return e}function ya(a){return xa(a)?a:[a]}function r(){var a=arguments,b,c,d=a.length;for(b=0;b<d;b++)if(c=a[b],c!==v&&null!==c)return c}function V(a,b){ia&&!S&&b&&b.opacity!==v&&(b.filter="alpha(opacity="+100*b.opacity+")");x(a.style,b)}function za(a,b,c,d,e){a=B.createElement(a);b&&x(a,b);e&&V(a,{padding:0,border:"none",margin:0});c&&V(a,c);d&&d.appendChild(a);return a}function Ga(a,b){var c=function(){return v};c.prototype=new a;x(c.prototype,b);return c}
function da(a,b,c,d){var e=T.numberFormat,f=J.lang,g=+a||0,h=-1===b?(g.toString().split(".")[1]||"").length:isNaN(b=P(b))?2:b,k=void 0===c?f.decimalPoint:c,f=void 0===d?f.thousandsSep:d,l=0>g?"-":"",m=String(z(g=P(g).toFixed(h))),n=3<m.length?m.length%3:0;return e!==da?e(a,b,c,d):l+(n?m.substr(0,n)+f:"")+m.substr(n).replace(/(\d{3})(?=\d)/g,"$1"+f)+(h?k+P(g-m).toFixed(h).slice(2):"")}function ja(a,b){return Array((b||2)+1-String(a).length).join(0)+a}function Ua(a,b,c){var d=a[b];a[b]=function(){var a=
Array.prototype.slice.call(arguments);a.unshift(d);return c.apply(this,a)}}function Ha(a,b){for(var c="{",d=!1,e,f,g,h,k,l=[];-1!==(c=a.indexOf(c));){e=a.slice(0,c);if(d){f=e.split(":");g=f.shift().split(".");k=g.length;e=b;for(h=0;h<k;h++)e=e[g[h]];f.length&&(f=f.join(":"),g=/\.([0-9])/,h=J.lang,k=void 0,/f$/.test(f)?(k=(k=f.match(g))?k[1]:-1,null!==e&&(e=da(e,k,h.decimalPoint,-1<f.indexOf(",")?h.thousandsSep:""))):e=Ia(f,e))}l.push(e);a=a.slice(c+1);c=(d=!d)?"}":"{"}l.push(a);return l.join("")}
function fb(a,b,c,d){var e;c=r(c,1);e=a/c;b||(b=[1,2,2.5,5,10],!1===d&&(1===c?b=[1,2,5,10]:.1>=c&&(b=[1/c])));for(d=0;d<b.length&&!(a=b[d],e<=(b[d]+(b[d+1]||b[d]))/2);d++);return a*c}function Va(a,b){var c=a.length,d,e;for(e=0;e<c;e++)a[e].ss_i=e;a.sort(function(a,c){d=b(a,c);return 0===d?a.ss_i-c.ss_i:d});for(e=0;e<c;e++)delete a[e].ss_i}function ra(a){for(var b=a.length,c=a[0];b--;)a[b]<c&&(c=a[b]);return c}function ka(a){for(var b=a.length,c=a[0];b--;)a[b]>c&&(c=a[b]);return c}function Aa(a,b){for(var c in a)a[c]&&
a[c]!==b&&a[c].destroy&&a[c].destroy(),delete a[c]}function Ja(a){Ka||(Ka=za("div"));a&&Ka.appendChild(a);Ka.innerHTML=""}function Z(a){return parseFloat(a.toPrecision(14))}function gb(){var a=J.global.useUTC,b=a?"getUTC":"get",c=a?"setUTC":"set";sa=J.global.Date||window.Date;ta=6E4*(a&&J.global.timezoneOffset||0);La=a?sa.UTC:function(a,b,c,g,h,k){return(new sa(a,b,r(c,1),r(g,0),r(h,0),r(k,0))).getTime()};Wa=b+"Minutes";Xa=b+"Hours";Ya=b+"Day";Ba=b+"Date";Ma=b+"Month";Na=b+"FullYear";hb=c+"Minutes";
ib=c+"Hours";Za=c+"Date";jb=c+"Month";kb=c+"FullYear"}function M(){}function ua(a,b,c,d){this.axis=a;this.pos=b;this.type=c||"";this.isNew=!0;c||d||this.addLabel()}function va(){this.init.apply(this,arguments)}function $a(){this.init.apply(this,arguments)}var v,B=document,F=window,H=Math,y=H.round,K=H.floor,la=H.ceil,w=H.max,N=H.min,P=H.abs,Ca=H.cos,Oa=H.sin,lb=H.PI,mb=2*lb/360,ma=navigator.userAgent,wb=F.opera,ia=/msie/i.test(ma)&&!wb,xb=/AppleWebKit/.test(ma),Pa=/Firefox/.test(ma),nb=/(Mobile|Android|Windows Phone)/.test(ma),
S=!!B.createElementNS&&!!B.createElementNS("http://www.w3.org/2000/svg","svg").createSVGRect,yb=Pa&&4>parseInt(ma.split("Firefox/")[1],10),$=!S&&!ia&&!!B.createElement("canvas").getContext,ob={},ab=0,Ka,J,Ia,W,bb,A,U,pb=function(){return v},ea=[],qb=0,zb=/^[0-9]+$/,sa,La,ta,Wa,Xa,Ya,Ba,Ma,Na,hb,ib,Za,jb,kb,na={},T;F.Highcharts?U(16,!0):T=F.Highcharts={};Ia=function(a,b,c){if(!u(b)||isNaN(b))return"Invalid date";a=r(a,"%Y-%m-%d %H:%M:%S");var d=new sa(b-ta),e,f=d[Xa](),g=d[Ya](),h=d[Ba](),k=d[Ma](),
l=d[Na](),m=J.lang,n=m.weekdays,d=x({a:n[g].substr(0,3),A:n[g],d:ja(h),e:h,b:m.shortMonths[k],B:m.months[k],m:ja(k+1),y:l.toString().substr(2,2),Y:l,H:ja(f),I:ja(f%12||12),l:f%12||12,M:ja(d[Wa]()),p:12>f?"AM":"PM",P:12>f?"am":"pm",S:ja(d.getSeconds()),L:ja(y(b%1E3),3)},T.dateFormats);for(e in d)for(;-1!==a.indexOf("%"+e);)a=a.replace("%"+e,"function"===typeof d[e]?d[e](b):d[e]);return c?a.substr(0,1).toUpperCase()+a.substr(1):a};U=function(a,b){var c="Highcharts error #"+a+": www.highcharts.com/errors/"+
a;if(b)throw c;F.console&&console.log(c)};A={millisecond:1,second:1E3,minute:6E4,hour:36E5,day:864E5,week:6048E5,month:26784E5,year:31556952E3};bb={init:function(a,b,c){b=b||"";var d=a.shift,e=-1<b.indexOf("C"),f=e?7:3,g;b=b.split(" ");c=[].concat(c);var h,k,l=function(a){for(g=a.length;g--;)"M"===a[g]&&a.splice(g+1,0,a[g+1],a[g+2],a[g+1],a[g+2])};e&&(l(b),l(c));a.isArea&&(h=b.splice(b.length-6,6),k=c.splice(c.length-6,6));if(d<=c.length/f&&b.length===c.length)for(;d--;)c=[].concat(c).splice(0,f).concat(c);
a.shift=0;if(b.length)for(a=c.length;b.length<a;)d=[].concat(b).splice(b.length-f,f),e&&(d[f-6]=d[f-2],d[f-5]=d[f-1]),b=b.concat(d);h&&(b=b.concat(h),c=c.concat(k));return[b,c]},step:function(a,b,c,d){var e=[],f=a.length;if(1===c)e=d;else if(f===b.length&&1>c)for(;f--;)d=parseFloat(a[f]),e[f]=isNaN(d)?a[f]:c*parseFloat(b[f]-d)+d;else e=b;return e}};(function(a){F.HighchartsAdapter=F.HighchartsAdapter||a&&{init:function(b){var c=a.fx;a.extend(a.easing,{easeOutQuad:function(a,b,c,g,h){return-g*(b/=
h)*(b-2)+c}});a.each(["cur","_default","width","height","opacity"],function(b,e){var f=c.step,g;"cur"===e?f=c.prototype:"_default"===e&&a.Tween&&(f=a.Tween.propHooks[e],e="set");(g=f[e])&&(f[e]=function(a){var c;a=b?a:this;if("align"!==a.prop)return c=a.elem,c.attr?c.attr(a.prop,"cur"===e?v:a.now):g.apply(this,arguments)})});Ua(a.cssHooks.opacity,"get",function(a,b,c){return b.attr?b.opacity||0:a.call(this,b,c)});this.addAnimSetter("d",function(a){var c=a.elem,f;a.started||(f=b.init(c,c.d,c.toD),
a.start=f[0],a.end=f[1],a.started=!0);c.attr("d",b.step(a.start,a.end,a.pos,c.toD))});this.each=Array.prototype.forEach?function(a,b){return Array.prototype.forEach.call(a,b)}:function(a,b){var c,g=a.length;for(c=0;c<g;c++)if(!1===b.call(a[c],a[c],c,a))return c};a.fn.highcharts=function(){var a="Chart",b=arguments,c,g;this[0]&&(ga(b[0])&&(a=b[0],b=Array.prototype.slice.call(b,1)),c=b[0],c!==v&&(c.chart=c.chart||{},c.chart.renderTo=this[0],new T[a](c,b[1]),g=this),c===v&&(g=ea[G(this[0],"data-highcharts-chart")]));
return g}},addAnimSetter:function(b,c){a.Tween?a.Tween.propHooks[b]={set:c}:a.fx.step[b]=c},getScript:a.getScript,inArray:a.inArray,adapterRun:function(b,c){return a(b)[c]()},grep:a.grep,map:function(a,c){for(var d=[],e=0,f=a.length;e<f;e++)d[e]=c.call(a[e],a[e],e,a);return d},offset:function(b){return a(b).offset()},addEvent:function(b,c,d){a(b).bind(c,d)},removeEvent:function(b,c,d){var e=B.removeEventListener?"removeEventListener":"detachEvent";B[e]&&b&&!b[e]&&(b[e]=function(){});a(b).unbind(c,
d)},fireEvent:function(b,c,d,e){var f=a.Event(c),g="detached"+c,h;!ia&&d&&(delete d.layerX,delete d.layerY,delete d.returnValue);x(f,d);b[c]&&(b[g]=b[c],b[c]=null);a.each(["preventDefault","stopPropagation"],function(a,b){var c=f[b];f[b]=function(){try{c.call(f)}catch(a){"preventDefault"===b&&(h=!0)}}});a(b).trigger(f);b[g]&&(b[c]=b[g],b[g]=null);!e||f.isDefaultPrevented()||h||e(f)},washMouseEvent:function(a){var c=a.originalEvent||a;c.pageX===v&&(c.pageX=a.pageX,c.pageY=a.pageY);return c},animate:function(b,
c,d){var e=a(b);b.style||(b.style={});c.d&&(b.toD=c.d,c.d=1);e.stop();c.opacity!==v&&b.attr&&(c.opacity+="px");b.hasAnim=1;e.animate(c,d)},stop:function(b){b.hasAnim&&a(b).stop()}}})(F.jQuery);var Qa=F.HighchartsAdapter,Y=Qa||{};Qa&&Qa.init.call(Qa,bb);var Ra=Y.adapterRun,Ab=Y.inArray,s=Y.each,cb=Y.grep,rb=Y.map,Q=Y.addEvent,X=Y.removeEvent,R=Y.fireEvent,sb=Y.animate,Sa=Y.stop,db={enabled:!0,x:0,y:15,style:{color:"#606060",cursor:"default",fontSize:"11px"}};J={colors:"#7cb5ec #434348 #90ed7d #f7a35c #8085e9 #f15c80 #e4d354 #8085e8 #8d4653 #91e8e1".split(" "),
symbols:["circle","diamond","square","triangle","triangle-down"],lang:{loading:"Loading...",months:"January February March April May June July August September October November December".split(" "),shortMonths:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),weekdays:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),decimalPoint:".",numericSymbols:"kMGTPE".split(""),resetZoom:"Reset zoom",resetZoomTitle:"Reset zoom level 1:1",thousandsSep:","},global:{useUTC:!0,canvasToolsURL:"http://code.highcharts.com@product.cdnpath@//Highstock 2.0.4/modules/canvas-tools.js",
VMLRadialGradientURL:"http://code.highcharts.com@product.cdnpath@//Highstock 2.0.4/gfx/vml-radial-gradient.png"},chart:{borderColor:"#4572A7",borderRadius:0,defaultSeriesType:"line",ignoreHiddenSeries:!0,spacing:[10,10,15,10],backgroundColor:"#FFFFFF",plotBorderColor:"#C0C0C0",resetZoomButton:{theme:{zIndex:20},position:{align:"right",x:-10,y:10}}},title:{text:"Chart title",align:"center",margin:15,style:{color:"#333333",fontSize:"18px"}},subtitle:{text:"",align:"center",style:{color:"#555555"}},
plotOptions:{line:{allowPointSelect:!1,showCheckbox:!1,animation:{duration:1E3},events:{},lineWidth:2,marker:{lineWidth:0,radius:4,lineColor:"#FFFFFF",states:{hover:{enabled:!0,lineWidthPlus:1,radiusPlus:2},select:{fillColor:"#FFFFFF",lineColor:"#000000",lineWidth:2}}},point:{events:{}},dataLabels:C(db,{align:"center",enabled:!1,formatter:function(){return null===this.y?"":da(this.y,-1)},verticalAlign:"bottom",y:0}),cropThreshold:300,pointRange:0,states:{hover:{lineWidthPlus:1,marker:{},halo:{size:10,
opacity:.25}},select:{marker:{}}},stickyTracking:!0,turboThreshold:1E3}},labels:{style:{position:"absolute",color:"#3E576F"}},legend:{enabled:!0,align:"center",layout:"horizontal",labelFormatter:function(){return this.name},borderColor:"#909090",borderRadius:0,navigation:{activeColor:"#274b6d",inactiveColor:"#CCC"},shadow:!1,itemStyle:{color:"#333333",fontSize:"12px",fontWeight:"bold"},itemHoverStyle:{color:"#000"},itemHiddenStyle:{color:"#CCC"},itemCheckboxStyle:{position:"absolute",width:"13px",
height:"13px"},symbolPadding:5,verticalAlign:"bottom",x:0,y:0,title:{style:{fontWeight:"bold"}}},loading:{labelStyle:{fontWeight:"bold",position:"relative",top:"45%"},style:{position:"absolute",backgroundColor:"white",opacity:.5,textAlign:"center"}},tooltip:{enabled:!0,animation:S,backgroundColor:"rgba(249, 249, 249, .85)",borderWidth:1,borderRadius:3,dateTimeLabelFormats:{millisecond:"%A, %b %e, %H:%M:%S.%L",second:"%A, %b %e, %H:%M:%S",minute:"%A, %b %e, %H:%M",hour:"%A, %b %e, %H:%M",day:"%A, %b %e, %Y",
week:"Week from %A, %b %e, %Y",month:"%B %Y",year:"%Y"},headerFormat:'<span style="font-size: 10px">{point.key}</span><br/>',pointFormat:'<span style="color:{series.color}">\u25cf</span> {series.name}: <b>{point.y}</b><br/>',shadow:!0,snap:nb?25:10,style:{color:"#333333",cursor:"default",fontSize:"12px",padding:"8px",whiteSpace:"nowrap"}},credits:{enabled:!0,text:"Highcharts.com",href:"http://www.highcharts.com",position:{align:"right",x:-10,verticalAlign:"bottom",y:-5},style:{cursor:"pointer",color:"#909090",
fontSize:"9px"}}};var oa=J.plotOptions,Bb=oa.line;gb();var Cb=/rgba\(\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]?(?:\.[0-9]+)?)\s*\)/,Db=/#([a-fA-F0-9]{2})([a-fA-F0-9]{2})([a-fA-F0-9]{2})/,Eb=/rgb\(\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*\)/,Da=function(a){var b=[],c,d;(function(a){a&&a.stops?d=rb(a.stops,function(a){return Da(a[1])}):(c=Cb.exec(a))?b=[z(c[1]),z(c[2]),z(c[3]),parseFloat(c[4],10)]:(c=Db.exec(a))?b=[z(c[1],16),z(c[2],16),z(c[3],16),1]:(c=Eb.exec(a))&&
(b=[z(c[1]),z(c[2]),z(c[3]),1])})(a);return{get:function(c){var f;d?(f=C(a),f.stops=[].concat(f.stops),s(d,function(a,b){f.stops[b]=[f.stops[b][0],a.get(c)]})):f=b&&!isNaN(b[0])?"rgb"===c?"rgb("+b[0]+","+b[1]+","+b[2]+")":"a"===c?b[3]:"rgba("+b.join(",")+")":a;return f},brighten:function(a){if(d)s(d,function(b){b.brighten(a)});else if(ba(a)&&0!==a){var c;for(c=0;3>c;c++)b[c]+=z(255*a),0>b[c]&&(b[c]=0),255<b[c]&&(b[c]=255)}return this},rgba:b,setOpacity:function(a){b[3]=a;return this}}};M.prototype=
{opacity:1,textProps:"fontSize fontWeight fontFamily color lineHeight width textDecoration textShadow HcTextStroke".split(" "),init:function(a,b){this.element="span"===b?za(b):B.createElementNS("http://www.w3.org/2000/svg",b);this.renderer=a},animate:function(a,b,c){b=r(b,W,!0);Sa(this);b?(b=C(b,{}),c&&(b.complete=c),sb(this,a,b)):(this.attr(a),c&&c());return this},colorGradient:function(a,b,c){var d=this.renderer,e,f,g,h,k,l,m,n,q,p,t=[];a.linearGradient?f="linearGradient":a.radialGradient&&(f="radialGradient");
if(f){g=a[f];h=d.gradients;l=a.stops;q=c.radialReference;xa(g)&&(a[f]=g={x1:g[0],y1:g[1],x2:g[2],y2:g[3],gradientUnits:"userSpaceOnUse"});"radialGradient"===f&&q&&!u(g.gradientUnits)&&(g=C(g,{cx:q[0]-q[2]/2+g.cx*q[2],cy:q[1]-q[2]/2+g.cy*q[2],r:g.r*q[2],gradientUnits:"userSpaceOnUse"}));for(p in g)"id"!==p&&t.push(p,g[p]);for(p in l)t.push(l[p]);t=t.join(",");h[t]?a=h[t].attr("id"):(g.id=a="highcharts-"+ab++,h[t]=k=d.createElement(f).attr(g).add(d.defs),k.stops=[],s(l,function(a){0===a[1].indexOf("rgba")?
(e=Da(a[1]),m=e.get("rgb"),n=e.get("a")):(m=a[1],n=1);a=d.createElement("stop").attr({offset:a[0],"stop-color":m,"stop-opacity":n}).add(k);k.stops.push(a)}));c.setAttribute(b,"url("+d.url+"#"+a+")")}},attr:function(a,b){var c,d,e=this.element,f,g=this,h;"string"===typeof a&&b!==v&&(c=a,a={},a[c]=b);if("string"===typeof a)g=(this[a+"Getter"]||this._defaultGetter).call(this,a,e);else{for(c in a)d=a[c],h=!1,this.symbolName&&/^(x|y|width|height|r|start|end|innerR|anchorX|anchorY)/.test(c)&&(f||(this.symbolAttr(a),
f=!0),h=!0),!this.rotation||"x"!==c&&"y"!==c||(this.doTransform=!0),h||(this[c+"Setter"]||this._defaultSetter).call(this,d,c,e),this.shadows&&/^(width|height|visibility|x|y|d|transform|cx|cy|r)$/.test(c)&&this.updateShadows(c,d);this.doTransform&&(this.updateTransform(),this.doTransform=!1)}return g},updateShadows:function(a,b){for(var c=this.shadows,d=c.length;d--;)c[d].setAttribute(a,"height"===a?w(b-(c[d].cutHeight||0),0):"d"===a?this.d:b)},addClass:function(a){var b=this.element,c=G(b,"class")||
"";-1===c.indexOf(a)&&G(b,"class",c+" "+a);return this},symbolAttr:function(a){var b=this;s("x y r start end width height innerR anchorX anchorY".split(" "),function(c){b[c]=r(a[c],b[c])});b.attr({d:b.renderer.symbols[b.symbolName](b.x,b.y,b.width,b.height,b)})},clip:function(a){return this.attr("clip-path",a?"url("+this.renderer.url+"#"+a.id+")":"none")},crisp:function(a){var b,c={},d,e=a.strokeWidth||this.strokeWidth||0;d=y(e)%2/2;a.x=K(a.x||this.x||0)+d;a.y=K(a.y||this.y||0)+d;a.width=K((a.width||
this.width||0)-2*d);a.height=K((a.height||this.height||0)-2*d);a.strokeWidth=e;for(b in a)this[b]!==a[b]&&(this[b]=c[b]=a[b]);return c},css:function(a){var b=this.styles,c={},d=this.element,e,f,g="";e=!b;a&&a.color&&(a.fill=a.color);if(b)for(f in a)a[f]!==b[f]&&(c[f]=a[f],e=!0);if(e){e=this.textWidth=a&&a.width&&"text"===d.nodeName.toLowerCase()&&z(a.width);b&&(a=x(b,c));this.styles=a;e&&($||!S&&this.renderer.forExport)&&delete a.width;if(ia&&!S)V(this.element,a);else{b=function(a,b){return"-"+b.toLowerCase()};
for(f in a)g+=f.replace(/([A-Z])/g,b)+":"+a[f]+";";G(d,"style",g)}e&&this.added&&this.renderer.buildText(this)}return this},on:function(a,b){this.element["on"+a]=b;return this},setRadialReference:function(a){this.element.radialReference=a;return this},translate:function(a,b){return this.attr({translateX:a,translateY:b})},invert:function(){this.inverted=!0;this.updateTransform();return this},updateTransform:function(){var a=this.translateX||0,b=this.translateY||0,c=this.scaleX,d=this.scaleY,e=this.inverted,
f=this.rotation,g=this.element;e&&(a+=this.attr("width"),b+=this.attr("height"));a=["translate("+a+","+b+")"];e?a.push("rotate(90) scale(-1,1)"):f&&a.push("rotate("+f+" "+(g.getAttribute("x")||0)+" "+(g.getAttribute("y")||0)+")");(u(c)||u(d))&&a.push("scale("+r(c,1)+" "+r(d,1)+")");a.length&&g.setAttribute("transform",a.join(" "))},toFront:function(){var a=this.element;a.parentNode.appendChild(a);return this},align:function(a,b,c){var d,e,f,g,h={};e=this.renderer;f=e.alignedObjects;if(a){if(this.alignOptions=
a,this.alignByTranslate=b,!c||ga(c))this.alignTo=d=c||"renderer",ha(f,this),f.push(this),c=null}else a=this.alignOptions,b=this.alignByTranslate,d=this.alignTo;c=r(c,e[d],e);d=a.align;e=a.verticalAlign;f=(c.x||0)+(a.x||0);g=(c.y||0)+(a.y||0);if("right"===d||"center"===d)f+=(c.width-(a.width||0))/{right:1,center:2}[d];h[b?"translateX":"x"]=y(f);if("bottom"===e||"middle"===e)g+=(c.height-(a.height||0))/({bottom:1,middle:2}[e]||1);h[b?"translateY":"y"]=y(g);this[this.placed?"animate":"attr"](h);this.placed=
!0;this.alignAttr=h;return this},getBBox:function(){var a=this.bBox,b=this.renderer,c,d,e=this.rotation;c=this.element;var f=this.styles,g=e*mb;d=this.textStr;var h;if(""===d||zb.test(d))h="num."+d.toString().length+(f?"|"+f.fontSize+"|"+f.fontFamily:"");h&&(a=b.cache[h]);if(!a){if("http://www.w3.org/2000/svg"===c.namespaceURI||b.forExport){try{a=c.getBBox?x({},c.getBBox()):{width:c.offsetWidth,height:c.offsetHeight}}catch(k){}if(!a||0>a.width)a={width:0,height:0}}else a=this.htmlGetBBox();b.isSVG&&
(c=a.width,d=a.height,ia&&f&&"11px"===f.fontSize&&"16.9"===d.toPrecision(3)&&(a.height=d=14),e&&(a.width=P(d*Oa(g))+P(c*Ca(g)),a.height=P(d*Ca(g))+P(c*Oa(g))));this.bBox=a;h&&(b.cache[h]=a)}return a},show:function(a){a&&"http://www.w3.org/2000/svg"===this.element.namespaceURI?this.element.removeAttribute("visibility"):this.attr({visibility:a?"inherit":"visible"});return this},hide:function(){return this.attr({visibility:"hidden"})},fadeOut:function(a){var b=this;b.animate({opacity:0},{duration:a||
150,complete:function(){b.attr({y:-9999})}})},add:function(a){var b=this.renderer,c=a||b,d=c.element||b.box,e=this.element,f=this.zIndex,g,h;a&&(this.parentGroup=a);this.parentInverted=a&&a.inverted;void 0!==this.textStr&&b.buildText(this);f&&(c.handleZ=!0,f=z(f));if(c.handleZ)for(a=d.childNodes,g=0;g<a.length;g++)if(b=a[g],c=G(b,"zIndex"),b!==e&&(z(c)>f||!u(f)&&u(c))){d.insertBefore(e,b);h=!0;break}h||d.appendChild(e);this.added=!0;if(this.onAdd)this.onAdd();return this},safeRemoveChild:function(a){var b=
a.parentNode;b&&b.removeChild(a)},destroy:function(){var a=this,b=a.element||{},c=a.shadows,d=a.renderer.isSVG&&"SPAN"===b.nodeName&&a.parentGroup,e,f;b.onclick=b.onmouseout=b.onmouseover=b.onmousemove=b.point=null;Sa(a);a.clipPath&&(a.clipPath=a.clipPath.destroy());if(a.stops){for(f=0;f<a.stops.length;f++)a.stops[f]=a.stops[f].destroy();a.stops=null}a.safeRemoveChild(b);for(c&&s(c,function(b){a.safeRemoveChild(b)});d&&d.div&&0===d.div.childNodes.length;)b=d.parentGroup,a.safeRemoveChild(d.div),delete d.div,
d=b;a.alignTo&&ha(a.renderer.alignedObjects,a);for(e in a)delete a[e];return null},shadow:function(a,b,c){var d=[],e,f,g=this.element,h,k,l,m;if(a){k=r(a.width,3);l=(a.opacity||.15)/k;m=this.parentInverted?"(-1,-1)":"("+r(a.offsetX,1)+", "+r(a.offsetY,1)+")";for(e=1;e<=k;e++)f=g.cloneNode(0),h=2*k+1-2*e,G(f,{isShadow:"true",stroke:a.color||"black","stroke-opacity":l*e,"stroke-width":h,transform:"translate"+m,fill:"none"}),c&&(G(f,"height",w(G(f,"height")-h,0)),f.cutHeight=h),b?b.element.appendChild(f):
g.parentNode.insertBefore(f,g),d.push(f);this.shadows=d}return this},xGetter:function(a){"circle"===this.element.nodeName&&(a={x:"cx",y:"cy"}[a]||a);return this._defaultGetter(a)},_defaultGetter:function(a){a=r(this[a],this.element?this.element.getAttribute(a):null,0);/^[\-0-9\.]+$/.test(a)&&(a=parseFloat(a));return a},dSetter:function(a,b,c){a&&a.join&&(a=a.join(" "));/(NaN| {2}|^$)/.test(a)&&(a="M 0 0");c.setAttribute(b,a);this[b]=a},dashstyleSetter:function(a){var b;if(a=a&&a.toLowerCase()){a=
a.replace("shortdashdotdot","3,1,1,1,1,1,").replace("shortdashdot","3,1,1,1").replace("shortdot","1,1,").replace("shortdash","3,1,").replace("longdash","8,3,").replace(/dot/g,"1,3,").replace("dash","4,3,").replace(/,$/,"").split(",");for(b=a.length;b--;)a[b]=z(a[b])*this["stroke-width"];a=a.join(",").replace("NaN","none");this.element.setAttribute("stroke-dasharray",a)}},alignSetter:function(a){this.element.setAttribute("text-anchor",{left:"start",center:"middle",right:"end"}[a])},opacitySetter:function(a,
b,c){this[b]=a;c.setAttribute(b,a)},titleSetter:function(a){var b=this.element.getElementsByTagName("title")[0];b||(b=B.createElementNS("http://www.w3.org/2000/svg","title"),this.element.appendChild(b));b.textContent=r(a,"").replace(/<[^>]*>/g,"")},textSetter:function(a){a!==this.textStr&&(delete this.bBox,this.textStr=a,this.added&&this.renderer.buildText(this))},fillSetter:function(a,b,c){"string"===typeof a?c.setAttribute(b,a):a&&this.colorGradient(a,b,c)},zIndexSetter:function(a,b,c){c.setAttribute(b,
a);this[b]=a},_defaultSetter:function(a,b,c){c.setAttribute(b,a)}};M.prototype.yGetter=M.prototype.xGetter;M.prototype.translateXSetter=M.prototype.translateYSetter=M.prototype.rotationSetter=M.prototype.verticalAlignSetter=M.prototype.scaleXSetter=M.prototype.scaleYSetter=function(a,b){this[b]=a;this.doTransform=!0};M.prototype["stroke-widthSetter"]=M.prototype.strokeSetter=function(a,b,c){this[b]=a;this.stroke&&this["stroke-width"]?(this.strokeWidth=this["stroke-width"],M.prototype.fillSetter.call(this,
this.stroke,"stroke",c),c.setAttribute("stroke-width",this["stroke-width"]),this.hasStroke=!0):"stroke-width"===b&&0===a&&this.hasStroke&&(c.removeAttribute("stroke"),this.hasStroke=!1)};var Ea=function(){this.init.apply(this,arguments)};Ea.prototype={Element:M,init:function(a,b,c,d,e){var f=location,g;d=this.createElement("svg").attr({version:"1.1"}).css(this.getStyle(d));g=d.element;a.appendChild(g);-1===a.innerHTML.indexOf("xmlns")&&G(g,"xmlns","http://www.w3.org/2000/svg");this.isSVG=!0;this.box=
g;this.boxWrapper=d;this.alignedObjects=[];this.url=(Pa||xb)&&B.getElementsByTagName("base").length?f.href.replace(/#.*?$/,"").replace(/([\('\)])/g,"\\$1").replace(/ /g,"%20"):"";this.createElement("desc").add().element.appendChild(B.createTextNode("Created with Highcharts 4.0.4 /Highstock 2.0.4"));this.defs=this.createElement("defs").add();this.forExport=e;this.gradients={};this.cache={};this.setSize(b,c,!1);var h;Pa&&a.getBoundingClientRect&&(this.subPixelFix=b=function(){V(a,{left:0,top:0});h=
a.getBoundingClientRect();V(a,{left:la(h.left)-h.left+"px",top:la(h.top)-h.top+"px"})},b(),Q(F,"resize",b))},getStyle:function(a){return this.style=x({fontFamily:'"Lucida Grande", "Lucida Sans Unicode", Arial, Helvetica, sans-serif',fontSize:"12px"},a)},isHidden:function(){return!this.boxWrapper.getBBox().width},destroy:function(){var a=this.defs;this.box=null;this.boxWrapper=this.boxWrapper.destroy();Aa(this.gradients||{});this.gradients=null;a&&(this.defs=a.destroy());this.subPixelFix&&X(F,"resize",
this.subPixelFix);return this.alignedObjects=null},createElement:function(a){var b=new this.Element;b.init(this,a);return b},draw:function(){},buildText:function(a){for(var b=a.element,c=this,d=c.forExport,e=r(a.textStr,"").toString(),f=-1!==e.indexOf("<"),g=b.childNodes,h,k,l=G(b,"x"),m=a.styles,n=a.textWidth,q=m&&m.lineHeight,p=m&&m.HcTextStroke,t=g.length,L=function(a){return q?z(q):c.fontMetrics(/(px|em)$/.test(a&&a.style.fontSize)?a.style.fontSize:m&&m.fontSize||c.style.fontSize||12,a).h};t--;)b.removeChild(g[t]);
f||p||-1!==e.indexOf(" ")?(h=/<.*style="([^"]+)".*>/,k=/<.*href="(http[^"]+)".*>/,n&&!a.added&&this.box.appendChild(b),e=f?e.replace(/<(b|strong)>/g,'<span style="font-weight:bold">').replace(/<(i|em)>/g,'<span style="font-style:italic">').replace(/<a/g,"<span").replace(/<\/(b|strong|i|em|a)>/g,"</span>").split(/<br.*?>/g):[e],""===e[e.length-1]&&e.pop(),s(e,function(e,f){var g,p=0;e=e.replace(/<span/g,"|||<span").replace(/<\/span>/g,"</span>|||");g=e.split("|||");s(g,function(e){if(""!==e||1===g.length){var q=
{},t=B.createElementNS("http://www.w3.org/2000/svg","tspan"),r;h.test(e)&&(r=e.match(h)[1].replace(/(;| |^)color([ :])/,"$1fill$2"),G(t,"style",r));k.test(e)&&!d&&(G(t,"onclick",'location.href="'+e.match(k)[1]+'"'),V(t,{cursor:"pointer"}));e=(e.replace(/<(.|\n)*?>/g,"")||" ").replace(/&lt;/g,"<").replace(/&gt;/g,">");if(" "!==e){t.appendChild(B.createTextNode(e));p?q.dx=0:f&&null!==l&&(q.x=l);G(t,q);b.appendChild(t);!p&&f&&(!S&&d&&V(t,{display:"block"}),G(t,"dy",L(t)));if(n){e=e.replace(/([^\^])-/g,
"$1- ").split(" ");for(var q=1<g.length||1<e.length&&"nowrap"!==m.whiteSpace,s,D,u=m.HcHeight,v=[],w=L(t),tb=1;q&&(e.length||v.length);)delete a.bBox,s=a.getBBox(),D=s.width,!S&&c.forExport&&(D=c.measureSpanWidth(t.firstChild.data,a.styles)),(s=D>n)&&1!==e.length?(t.removeChild(t.firstChild),v.unshift(e.pop())):(e=v,v=[],e.length&&(tb++,u&&tb*w>u?(e=["..."],a.attr("title",a.textStr)):(t=B.createElementNS("http://www.w3.org/2000/svg","tspan"),G(t,{dy:w,x:l}),r&&G(t,"style",r),b.appendChild(t))),D>
n&&(n=D)),e.length&&t.appendChild(B.createTextNode(e.join(" ").replace(/- /g,"-")))}p++}}})})):b.appendChild(B.createTextNode(e))},button:function(a,b,c,d,e,f,g,h,k){var l=this.label(a,b,c,k,null,null,null,null,"button"),m=0,n,q,p,t,r,s;a={x1:0,y1:0,x2:0,y2:1};e=C({"stroke-width":1,stroke:"#CCCCCC",fill:{linearGradient:a,stops:[[0,"#FEFEFE"],[1,"#F6F6F6"]]},r:2,padding:5,style:{color:"black"}},e);p=e.style;delete e.style;f=C(e,{stroke:"#68A",fill:{linearGradient:a,stops:[[0,"#FFF"],[1,"#ACF"]]}},
f);t=f.style;delete f.style;g=C(e,{stroke:"#68A",fill:{linearGradient:a,stops:[[0,"#9BD"],[1,"#CDF"]]}},g);r=g.style;delete g.style;h=C(e,{style:{color:"#CCC"}},h);s=h.style;delete h.style;Q(l.element,ia?"mouseover":"mouseenter",function(){3!==m&&l.attr(f).css(t)});Q(l.element,ia?"mouseout":"mouseleave",function(){3!==m&&(n=[e,f,g][m],q=[p,t,r][m],l.attr(n).css(q))});l.setState=function(a){(l.state=m=a)?2===a?l.attr(g).css(r):3===a&&l.attr(h).css(s):l.attr(e).css(p)};return l.on("click",function(){3!==
m&&d.call(l)}).attr(e).css(x({cursor:"default"},p))},crispLine:function(a,b){a[1]===a[4]&&(a[1]=a[4]=y(a[1])-b%2/2);a[2]===a[5]&&(a[2]=a[5]=y(a[2])+b%2/2);return a},path:function(a){var b={fill:"none"};xa(a)?b.d=a:aa(a)&&x(b,a);return this.createElement("path").attr(b)},circle:function(a,b,c){a=aa(a)?a:{x:a,y:b,r:c};b=this.createElement("circle");b.xSetter=function(a){this.element.setAttribute("cx",a)};b.ySetter=function(a){this.element.setAttribute("cy",a)};return b.attr(a)},arc:function(a,b,c,d,
e,f){aa(a)&&(b=a.y,c=a.r,d=a.innerR,e=a.start,f=a.end,a=a.x);a=this.symbol("arc",a||0,b||0,c||0,c||0,{innerR:d||0,start:e||0,end:f||0});a.r=c;return a},rect:function(a,b,c,d,e,f){e=aa(a)?a.r:e;var g=this.createElement("rect");a=aa(a)?a:a===v?{}:{x:a,y:b,width:w(c,0),height:w(d,0)};f!==v&&(a.strokeWidth=f,a=g.crisp(a));e&&(a.r=e);g.rSetter=function(a){G(this.element,{rx:a,ry:a})};return g.attr(a)},setSize:function(a,b,c){var d=this.alignedObjects,e=d.length;this.width=a;this.height=b;for(this.boxWrapper[r(c,
!0)?"animate":"attr"]({width:a,height:b});e--;)d[e].align()},g:function(a){var b=this.createElement("g");return u(a)?b.attr({"class":"highcharts-"+a}):b},image:function(a,b,c,d,e){var f={preserveAspectRatio:"none"};1<arguments.length&&x(f,{x:b,y:c,width:d,height:e});f=this.createElement("image").attr(f);f.element.setAttributeNS?f.element.setAttributeNS("http://www.w3.org/1999/xlink","href",a):f.element.setAttribute("hc-svg-href",a);return f},symbol:function(a,b,c,d,e,f){var g,h=this.symbols[a],h=
h&&h(y(b),y(c),d,e,f),k=/^url\((.*?)\)$/,l,m;h?(g=this.path(h),x(g,{symbolName:a,x:b,y:c,width:d,height:e}),f&&x(g,f)):k.test(a)&&(m=function(a,b){a.element&&(a.attr({width:b[0],height:b[1]}),a.alignByTranslate||a.translate(y((d-b[0])/2),y((e-b[1])/2)))},l=a.match(k)[1],a=ob[l]||f&&f.width&&f.height&&[f.width,f.height],g=this.image(l).attr({x:b,y:c}),g.isImg=!0,a?m(g,a):(g.attr({width:0,height:0}),za("img",{onload:function(){m(g,ob[l]=[this.width,this.height])},src:l})));return g},symbols:{circle:function(a,
b,c,d){var e=.166*c;return["M",a+c/2,b,"C",a+c+e,b,a+c+e,b+d,a+c/2,b+d,"C",a-e,b+d,a-e,b,a+c/2,b,"Z"]},square:function(a,b,c,d){return["M",a,b,"L",a+c,b,a+c,b+d,a,b+d,"Z"]},triangle:function(a,b,c,d){return["M",a+c/2,b,"L",a+c,b+d,a,b+d,"Z"]},"triangle-down":function(a,b,c,d){return["M",a,b,"L",a+c,b,a+c/2,b+d,"Z"]},diamond:function(a,b,c,d){return["M",a+c/2,b,"L",a+c,b+d/2,a+c/2,b+d,a,b+d/2,"Z"]},arc:function(a,b,c,d,e){var f=e.start;c=e.r||c||d;var g=e.end-.001;d=e.innerR;var h=e.open,k=Ca(f),l=
Oa(f),m=Ca(g),g=Oa(g);e=e.end-f<lb?0:1;return["M",a+c*k,b+c*l,"A",c,c,0,e,1,a+c*m,b+c*g,h?"M":"L",a+d*m,b+d*g,"A",d,d,0,e,0,a+d*k,b+d*l,h?"":"Z"]},callout:function(a,b,c,d,e){var f=N(e&&e.r||0,c,d),g=f+6,h=e&&e.anchorX,k=e&&e.anchorY;e=y(e.strokeWidth||0)%2/2;a+=e;b+=e;e=["M",a+f,b,"L",a+c-f,b,"C",a+c,b,a+c,b,a+c,b+f,"L",a+c,b+d-f,"C",a+c,b+d,a+c,b+d,a+c-f,b+d,"L",a+f,b+d,"C",a,b+d,a,b+d,a,b+d-f,"L",a,b+f,"C",a,b,a,b,a+f,b];h&&h>c&&k>b+g&&k<b+d-g?e.splice(13,3,"L",a+c,k-6,a+c+6,k,a+c,k+6,a+c,b+d-
f):h&&0>h&&k>b+g&&k<b+d-g?e.splice(33,3,"L",a,k+6,a-6,k,a,k-6,a,b+f):k&&k>d&&h>a+g&&h<a+c-g?e.splice(23,3,"L",h+6,b+d,h,b+d+6,h-6,b+d,a+f,b+d):k&&0>k&&h>a+g&&h<a+c-g&&e.splice(3,3,"L",h-6,b,h,b-6,h+6,b,c-f,b);return e}},clipRect:function(a,b,c,d){var e="highcharts-"+ab++,f=this.createElement("clipPath").attr({id:e}).add(this.defs);a=this.rect(a,b,c,d,0).add(f);a.id=e;a.clipPath=f;return a},text:function(a,b,c,d){var e=$||!S&&this.forExport,f={};if(d&&!this.forExport)return this.html(a,b,c);f.x=Math.round(b||
0);c&&(f.y=Math.round(c));if(a||0===a)f.text=a;a=this.createElement("text").attr(f);e&&a.css({position:"absolute"});d||(a.xSetter=function(a,b,c){var d=c.getElementsByTagName("tspan"),e,f=c.getAttribute(b),q;for(q=0;q<d.length;q++)e=d[q],e.getAttribute(b)===f&&e.setAttribute(b,a);c.setAttribute(b,a)});return a},fontMetrics:function(a,b){a=a||this.style.fontSize;b&&F.getComputedStyle&&(b=b.element||b,a=F.getComputedStyle(b,"").fontSize);a=/px/.test(a)?z(a):/em/.test(a)?12*parseFloat(a):12;var c=24>
a?a+4:y(1.2*a),d=y(.8*c);return{h:c,b:d,f:a}},label:function(a,b,c,d,e,f,g,h,k){function l(){var a,b;a=t.element.style;D=(void 0===wa||void 0===A||p.styles.textAlign)&&t.textStr&&t.getBBox();p.width=(wa||D.width||0)+2*E+w;p.height=(A||D.height||0)+2*E;fa=E+q.fontMetrics(a&&a.fontSize,t).b;F&&(r||(a=y(-Fa*E),b=h?-fa:0,p.box=r=d?q.symbol(d,a,b,p.width,p.height,O):q.rect(a,b,p.width,p.height,0,O["stroke-width"]),r.attr("fill","none").add(p)),r.isImg||r.attr(x({width:y(p.width),height:y(p.height)},O)),
O=null)}function m(){var a=p.styles,a=a&&a.textAlign,b=w+E*(1-Fa),c;c=h?0:fa;u(wa)&&D&&("center"===a||"right"===a)&&(b+={center:.5,right:1}[a]*(wa-D.width));if(b!==t.x||c!==t.y)t.attr("x",b),c!==v&&t.attr("y",c);t.x=b;t.y=c}function n(a,b){r?r.attr(a,b):O[a]=b}var q=this,p=q.g(k),t=q.text("",0,0,g).attr({zIndex:1}),r,D,Fa=0,E=3,w=0,wa,A,z,B,G=0,O={},fa,F;p.onAdd=function(){t.add(p);p.attr({text:a||0===a?a:"",x:b,y:c});r&&u(e)&&p.attr({anchorX:e,anchorY:f})};p.widthSetter=function(a){wa=a};p.heightSetter=
function(a){A=a};p.paddingSetter=function(a){u(a)&&a!==E&&(E=a,m())};p.paddingLeftSetter=function(a){u(a)&&a!==w&&(w=a,m())};p.alignSetter=function(a){Fa={left:0,center:.5,right:1}[a]};p.textSetter=function(a){a!==v&&t.textSetter(a);l();m()};p["stroke-widthSetter"]=function(a,b){a&&(F=!0);G=a%2/2;n(b,a)};p.strokeSetter=p.fillSetter=p.rSetter=function(a,b){"fill"===b&&a&&(F=!0);n(b,a)};p.anchorXSetter=function(a,b){e=a;n(b,a+G-z)};p.anchorYSetter=function(a,b){f=a;n(b,a-B)};p.xSetter=function(a){p.x=
a;Fa&&(a-=Fa*((wa||D.width)+E));z=y(a);p.attr("translateX",z)};p.ySetter=function(a){B=p.y=y(a);p.attr("translateY",B)};var H=p.css;return x(p,{css:function(a){if(a){var b={};a=C(a);s(p.textProps,function(c){a[c]!==v&&(b[c]=a[c],delete a[c])});t.css(b)}return H.call(p,a)},getBBox:function(){return{width:D.width+2*E,height:D.height+2*E,x:D.x-E,y:D.y-E}},shadow:function(a){r&&r.shadow(a);return p},destroy:function(){X(p.element,"mouseenter");X(p.element,"mouseleave");t&&(t=t.destroy());r&&(r=r.destroy());
M.prototype.destroy.call(p);p=q=l=m=n=null}})}};ua.prototype={addLabel:function(){var a=this.axis,b=a.options,c=a.chart,d=a.horiz,e=a.categories,f=a.names,g=this.pos,h=b.labels,k=h.rotation,l=a.tickPositions,d=d&&e&&!h.step&&!h.staggerLines&&!h.rotation&&c.plotWidth/l.length||!d&&(c.margin[3]||.33*c.chartWidth),m=g===l[0],n=g===l[l.length-1],q,f=e?r(e[g],f[g],g):g,e=this.label,p=l.info;a.isDatetimeAxis&&p&&(q=b.dateTimeLabelFormats[p.higherRanks[g]||p.unitName]);this.isFirst=m;this.isLast=n;b=a.labelFormatter.call({axis:a,
chart:c,isFirst:m,isLast:n,dateTimeLabelFormat:q,value:a.isLog?Z(ca(f)):f});g=d&&{width:w(1,y(d-2*(h.padding||10)))+"px"};u(e)?e&&e.attr({text:b}).css(g):(q={align:a.labelAlign},ba(k)&&(q.rotation=k),d&&h.ellipsis&&(g.HcHeight=a.len/l.length),this.label=e=u(b)&&h.enabled?c.renderer.text(b,0,0,h.useHTML).attr(q).css(x(g,h.style)).add(a.labelGroup):null,a.tickBaseline=c.renderer.fontMetrics(h.style.fontSize,e).b,k&&2===a.side&&(a.tickBaseline*=Ca(k*mb)));this.yOffset=e?r(h.y,a.tickBaseline+(2===a.side?
8:-(e.getBBox().height/2))):0},getLabelSize:function(){var a=this.label,b=this.axis;return a?a.getBBox()[b.horiz?"height":"width"]:0},getLabelSides:function(){var a=this.label.getBBox(),b=this.axis,c=b.horiz,d=b.options.labels,a=c?a.width:a.height,b=c?d.x-a*{left:0,center:.5,right:1}[b.labelAlign]:0;return[b,c?a+b:a]},handleOverflow:function(a,b){var c=!0,d=this.axis,e=this.isFirst,f=this.isLast,g=d.horiz?b.x:b.y,h=d.reversed,k=d.tickPositions,l=this.getLabelSides(),m=l[0],l=l[1],n,q,p,t=this.label.line;
n=t||0;q=d.labelEdge;p=d.justifyLabels&&(e||f);q[n]===v||g+m>q[n]?q[n]=g+l:p||(c=!1);if(p){n=(q=d.justifyToPlot)?d.pos:0;q=q?n+d.len:d.chart.chartWidth;do a+=e?1:-1,p=d.ticks[k[a]];while(k[a]&&(!p||!p.label||p.label.line!==t));d=p&&p.label.xy&&p.label.xy.x+p.getLabelSides()[e?0:1];e&&!h||f&&h?g+m<n&&(g=n-m,p&&g+l>d&&(c=!1)):g+l>q&&(g=q-l,p&&g+m<d&&(c=!1));b.x=g}return c},getPosition:function(a,b,c,d){var e=this.axis,f=e.chart,g=d&&f.oldChartHeight||f.chartHeight;return{x:a?e.translate(b+c,null,null,
d)+e.transB:e.left+e.offset+(e.opposite?(d&&f.oldChartWidth||f.chartWidth)-e.right-e.left:0),y:a?g-e.bottom+e.offset-(e.opposite?e.height:0):g-e.translate(b+c,null,null,d)-e.transB}},getLabelPosition:function(a,b,c,d,e,f,g,h){var k=this.axis,l=k.transA,m=k.reversed,n=k.staggerLines;a=a+e.x-(f&&d?f*l*(m?-1:1):0);b=b+this.yOffset-(f&&!d?f*l*(m?1:-1):0);n&&(c.line=g/(h||1)%n,b+=k.labelOffset/n*c.line);return{x:a,y:b}},getMarkPath:function(a,b,c,d,e,f){return f.crispLine(["M",a,b,"L",a+(e?0:-c),b+(e?
c:0)],d)},render:function(a,b,c){var d=this.axis,e=d.options,f=d.chart.renderer,g=d.horiz,h=this.type,k=this.label,l=this.pos,m=e.labels,n=this.gridLine,q=h?h+"Grid":"grid",p=h?h+"Tick":"tick",t=e[q+"LineWidth"],s=e[q+"LineColor"],D=e[q+"LineDashStyle"],u=e[p+"Length"],q=e[p+"Width"]||0,E=e[p+"Color"],w=e[p+"Position"],p=this.mark,y=m.step,x=!0,A=d.tickmarkOffset,z=this.getPosition(g,l,A,b),B=z.x,z=z.y,O=g&&B===d.pos+d.len||!g&&z===d.pos?-1:1;c=r(c,1);this.isActive=!0;if(t&&(l=d.getPlotLinePath(l+
A,t*O,b,!0),n===v&&(n={stroke:s,"stroke-width":t},D&&(n.dashstyle=D),h||(n.zIndex=1),b&&(n.opacity=0),this.gridLine=n=t?f.path(l).attr(n).add(d.gridGroup):null),!b&&n&&l))n[this.isNew?"attr":"animate"]({d:l,opacity:c});q&&u&&("inside"===w&&(u=-u),d.opposite&&(u=-u),h=this.getMarkPath(B,z,u,q*O,g,f),p?p.animate({d:h,opacity:c}):this.mark=f.path(h).attr({stroke:E,"stroke-width":q,opacity:c}).add(d.axisGroup));k&&!isNaN(B)&&(k.xy=z=this.getLabelPosition(B,z,k,g,m,A,a,y),this.isFirst&&!this.isLast&&!r(e.showFirstLabel,
1)||this.isLast&&!this.isFirst&&!r(e.showLastLabel,1)?x=!1:d.isRadial||m.step||m.rotation||b||0===c||(x=this.handleOverflow(a,z)),y&&a%y&&(x=!1),x&&!isNaN(z.y)?(z.opacity=c,k[this.isNew?"attr":"animate"](z),this.isNew=!1):k.attr("y",-9999))},destroy:function(){Aa(this,this.axis)}};T.PlotLineOrBand=function(a,b){this.axis=a;b&&(this.options=b,this.id=b.id)};T.PlotLineOrBand.prototype={render:function(){var a=this,b=a.axis,c=b.horiz,d=(b.pointRange||0)/2,e=a.options,f=e.label,g=a.label,h=e.width,k=
e.to,l=e.from,m=u(l)&&u(k),n=e.value,q=e.dashStyle,p=a.svgElem,t=[],r,s=e.color,v=e.zIndex,E=e.events,I={},y=b.chart.renderer;b.isLog&&(l=qa(l),k=qa(k),n=qa(n));if(h)t=b.getPlotLinePath(n,h),I={stroke:s,"stroke-width":h},q&&(I.dashstyle=q);else if(m)l=w(l,b.min-d),k=N(k,b.max+d),t=b.getPlotBandPath(l,k,e),s&&(I.fill=s),e.borderWidth&&(I.stroke=e.borderColor,I["stroke-width"]=e.borderWidth);else return;u(v)&&(I.zIndex=v);if(p)t?p.animate({d:t},null,p.onGetPath):(p.hide(),p.onGetPath=function(){p.show()},
g&&(a.label=g=g.destroy()));else if(t&&t.length&&(a.svgElem=p=y.path(t).attr(I).add(),E))for(r in d=function(b){p.on(b,function(c){E[b].apply(a,[c])})},E)d(r);f&&u(f.text)&&t&&t.length&&0<b.width&&0<b.height?(f=C({align:c&&m&&"center",x:c?!m&&4:10,verticalAlign:!c&&m&&"middle",y:c?m?16:10:m?6:-4,rotation:c&&!m&&90},f),g||(I={align:f.textAlign||f.align,rotation:f.rotation},u(v)&&(I.zIndex=v),a.label=g=y.text(f.text,0,0,f.useHTML).attr(I).css(f.style).add()),b=[t[1],t[4],m?t[6]:t[1]],m=[t[2],t[5],m?
t[7]:t[2]],t=ra(b),c=ra(m),g.align(f,!1,{x:t,y:c,width:ka(b)-t,height:ka(m)-c}),g.show()):g&&g.hide();return a},destroy:function(){ha(this.axis.plotLinesAndBands,this);delete this.axis;Aa(this)}};va.prototype={defaultOptions:{dateTimeLabelFormats:{millisecond:"%H:%M:%S.%L",second:"%H:%M:%S",minute:"%H:%M",hour:"%H:%M",day:"%e. %b",week:"%e. %b",month:"%b '%y",year:"%Y"},endOnTick:!1,gridLineColor:"#C0C0C0",labels:db,lineColor:"#C0D0E0",lineWidth:1,minPadding:.01,maxPadding:.01,minorGridLineColor:"#E0E0E0",
minorGridLineWidth:1,minorTickColor:"#A0A0A0",minorTickLength:2,minorTickPosition:"outside",startOfWeek:1,startOnTick:!1,tickColor:"#C0D0E0",tickLength:10,tickmarkPlacement:"between",tickPixelInterval:100,tickPosition:"outside",tickWidth:1,title:{align:"middle",style:{color:"#707070"}},type:"linear"},defaultYAxisOptions:{endOnTick:!0,gridLineWidth:1,tickPixelInterval:72,showLastLabel:!0,labels:{x:-8,y:3},lineWidth:0,maxPadding:.05,minPadding:.05,startOnTick:!0,tickWidth:0,title:{rotation:270,text:"Values"},
stackLabels:{enabled:!1,formatter:function(){return da(this.total,-1)},style:db.style}},defaultLeftAxisOptions:{labels:{x:-15,y:null},title:{rotation:270}},defaultRightAxisOptions:{labels:{x:15,y:null},title:{rotation:90}},defaultBottomAxisOptions:{labels:{x:0,y:null},title:{rotation:0}},defaultTopAxisOptions:{labels:{x:0,y:-15},title:{rotation:0}},init:function(a,b){var c=b.isX;this.horiz=a.inverted?!c:c;this.coll=(this.isXAxis=c)?"xAxis":"yAxis";this.opposite=b.opposite;this.side=b.side||(this.horiz?
this.opposite?0:2:this.opposite?1:3);this.setOptions(b);var d=this.options,e=d.type;this.labelFormatter=d.labels.formatter||this.defaultLabelFormatter;this.userOptions=b;this.minPixelPadding=0;this.chart=a;this.reversed=d.reversed;this.zoomEnabled=!1!==d.zoomEnabled;this.categories=d.categories||"category"===e;this.names=[];this.isLog="logarithmic"===e;this.isDatetimeAxis="datetime"===e;this.isLinked=u(d.linkedTo);this.tickmarkOffset=this.categories&&"between"===d.tickmarkPlacement&&1===r(d.tickInterval,
1)?.5:0;this.ticks={};this.labelEdge=[];this.minorTicks={};this.plotLinesAndBands=[];this.alternateBands={};this.len=0;this.minRange=this.userMinRange=d.minRange||d.maxZoom;this.range=d.range;this.offset=d.offset||0;this.stacks={};this.oldStacks={};this.min=this.max=null;this.crosshair=r(d.crosshair,ya(a.options.tooltip.crosshairs)[c?0:1],!1);var f,d=this.options.events;-1===Ab(this,a.axes)&&(c&&!this.isColorAxis?a.axes.splice(a.xAxis.length,0,this):a.axes.push(this),a[this.coll].push(this));this.series=
this.series||[];a.inverted&&c&&this.reversed===v&&(this.reversed=!0);this.removePlotLine=this.removePlotBand=this.removePlotBandOrLine;for(f in d)Q(this,f,d[f]);this.isLog&&(this.val2lin=qa,this.lin2val=ca)},setOptions:function(a){this.options=C(this.defaultOptions,this.isXAxis?{}:this.defaultYAxisOptions,[this.defaultTopAxisOptions,this.defaultRightAxisOptions,this.defaultBottomAxisOptions,this.defaultLeftAxisOptions][this.side],C(J[this.coll],a))},defaultLabelFormatter:function(){var a=this.axis,
b=this.value,c=a.categories,d=this.dateTimeLabelFormat,e=J.lang.numericSymbols,f=e&&e.length,g,h=a.options.labels.format,a=a.isLog?b:a.tickInterval;if(h)g=Ha(h,this);else if(c)g=b;else if(d)g=Ia(d,b);else if(f&&1E3<=a)for(;f--&&g===v;)c=Math.pow(1E3,f+1),a>=c&&null!==e[f]&&(g=da(b/c,-1)+e[f]);g===v&&(g=1E4<=P(b)?da(b,0):da(b,-1,v,""));return g},getSeriesExtremes:function(){var a=this,b=a.chart;a.hasVisibleSeries=!1;a.dataMin=a.dataMax=a.ignoreMinPadding=a.ignoreMaxPadding=null;a.buildStacks&&a.buildStacks();
s(a.series,function(c){if(c.visible||!b.options.chart.ignoreHiddenSeries){var d;d=c.options.threshold;var e;a.hasVisibleSeries=!0;a.isLog&&0>=d&&(d=null);a.isXAxis?(d=c.xData,d.length&&(a.dataMin=N(r(a.dataMin,d[0]),ra(d)),a.dataMax=w(r(a.dataMax,d[0]),ka(d)))):(c.getExtremes(),e=c.dataMax,c=c.dataMin,u(c)&&u(e)&&(a.dataMin=N(r(a.dataMin,c),c),a.dataMax=w(r(a.dataMax,e),e)),u(d)&&(a.dataMin>=d?(a.dataMin=d,a.ignoreMinPadding=!0):a.dataMax<d&&(a.dataMax=d,a.ignoreMaxPadding=!0)))}})},translate:function(a,
b,c,d,e,f){var g=1,h=0,k=d?this.oldTransA:this.transA;d=d?this.oldMin:this.min;var l=this.minPixelPadding;e=(this.options.ordinal||this.isLog&&e)&&this.lin2val;k||(k=this.transA);c&&(g*=-1,h=this.len);this.reversed&&(g*=-1,h-=g*(this.sector||this.len));b?(a=a*g+h-l,a=a/k+d,e&&(a=this.lin2val(a))):(e&&(a=this.val2lin(a)),"between"===f&&(f=.5),a=g*(a-d)*k+h+g*l+(ba(f)?k*f*this.pointRange:0));return a},toPixels:function(a,b){return this.translate(a,!1,!this.horiz,null,!0)+(b?0:this.pos)},toValue:function(a,
b){return this.translate(a-(b?0:this.pos),!0,!this.horiz,null,!0)},getPlotLinePath:function(a,b,c,d,e){var f=this.chart,g=this.left,h=this.top,k,l,m=c&&f.oldChartHeight||f.chartHeight,n=c&&f.oldChartWidth||f.chartWidth,q;k=this.transB;e=r(e,this.translate(a,null,null,c));a=c=y(e+k);k=l=y(m-e-k);if(isNaN(e))q=!0;else if(this.horiz){if(k=h,l=m-this.bottom,a<g||a>g+this.width)q=!0}else if(a=g,c=n-this.right,k<h||k>h+this.height)q=!0;return q&&!d?null:f.renderer.crispLine(["M",a,k,"L",c,l],b||1)},getLinearTickPositions:function(a,
b,c){var d,e=Z(K(b/a)*a),f=Z(la(c/a)*a),g=[];if(b===c&&ba(b))return[b];for(b=e;b<=f;){g.push(b);b=Z(b+a);if(b===d)break;d=b}return g},getMinorTickPositions:function(){var a=this.options,b=this.tickPositions,c=this.minorTickInterval,d=[],e;if(this.isLog)for(e=b.length,a=1;a<e;a++)d=d.concat(this.getLogTickPositions(c,b[a-1],b[a],!0));else if(this.isDatetimeAxis&&"auto"===a.minorTickInterval)d=d.concat(this.getTimeTicks(this.normalizeTimeTickInterval(c),this.min,this.max,a.startOfWeek)),d[0]<this.min&&
d.shift();else for(b=this.min+(b[0]-this.min)%c;b<=this.max;b+=c)d.push(b);return d},adjustForMinRange:function(){var a=this.options,b=this.min,c=this.max,d,e=this.dataMax-this.dataMin>=this.minRange,f,g,h,k,l;this.isXAxis&&this.minRange===v&&!this.isLog&&(u(a.min)||u(a.max)?this.minRange=null:(s(this.series,function(a){k=a.xData;for(g=l=a.xIncrement?1:k.length-1;0<g;g--)if(h=k[g]-k[g-1],f===v||h<f)f=h}),this.minRange=N(5*f,this.dataMax-this.dataMin)));if(c-b<this.minRange){var m=this.minRange;d=
(m-c+b)/2;d=[b-d,r(a.min,b-d)];e&&(d[2]=this.dataMin);b=ka(d);c=[b+m,r(a.max,b+m)];e&&(c[2]=this.dataMax);c=ra(c);c-b<m&&(d[0]=c-m,d[1]=r(a.min,c-m),b=ka(d))}this.min=b;this.max=c},setAxisTranslation:function(a){var b=this,c=b.max-b.min,d=b.axisPointRange||0,e,f=0,g=0,h=b.linkedParent,k=!!b.categories,l=b.transA;if(b.isXAxis||k||d)h?(f=h.minPointOffset,g=h.pointRangePadding):s(b.series,function(a){var h=k?1:b.isXAxis?a.pointRange:b.axisPointRange||0,l=a.options.pointPlacement,p=a.closestPointRange;
h>c&&(h=0);d=w(d,h);f=w(f,ga(l)?0:h/2);g=w(g,"on"===l?0:h);!a.noSharedTooltip&&u(p)&&(e=u(e)?N(e,p):p)}),h=b.ordinalSlope&&e?b.ordinalSlope/e:1,b.minPointOffset=f*=h,b.pointRangePadding=g*=h,b.pointRange=N(d,c),b.closestPointRange=e;a&&(b.oldTransA=l);b.translationSlope=b.transA=l=b.len/(c+g||1);b.transB=b.horiz?b.left:b.bottom;b.minPixelPadding=l*f},setTickPositions:function(a){var b=this,c=b.chart,d=b.options,e=d.startOnTick,f=d.endOnTick,g=b.isLog,h=b.isDatetimeAxis,k=b.isXAxis,l=b.isLinked,m=
b.options.tickPositioner,n=d.maxPadding,q=d.minPadding,p=d.tickInterval,t=d.minTickInterval,L=d.tickPixelInterval,D,v=b.categories;l?(b.linkedParent=c[b.coll][d.linkedTo],c=b.linkedParent.getExtremes(),b.min=r(c.min,c.dataMin),b.max=r(c.max,c.dataMax),d.type!==b.linkedParent.options.type&&U(11,1)):(b.min=r(b.userMin,d.min,b.dataMin),b.max=r(b.userMax,d.max,b.dataMax));g&&(!a&&0>=N(b.min,r(b.dataMin,b.min))&&U(10,1),b.min=Z(qa(b.min)),b.max=Z(qa(b.max)));b.range&&u(b.max)&&(b.userMin=b.min=w(b.min,
b.max-b.range),b.userMax=b.max,b.range=null);b.beforePadding&&b.beforePadding();b.adjustForMinRange();!(v||b.axisPointRange||b.usePercentage||l)&&u(b.min)&&u(b.max)&&(c=b.max-b.min)&&(u(d.min)||u(b.userMin)||!q||!(0>b.dataMin)&&b.ignoreMinPadding||(b.min-=c*q),u(d.max)||u(b.userMax)||!n||!(0<b.dataMax)&&b.ignoreMaxPadding||(b.max+=c*n));ba(d.floor)&&(b.min=w(b.min,d.floor));ba(d.ceiling)&&(b.max=N(b.max,d.ceiling));b.min===b.max||void 0===b.min||void 0===b.max?b.tickInterval=1:l&&!p&&L===b.linkedParent.options.tickPixelInterval?
b.tickInterval=b.linkedParent.tickInterval:(b.tickInterval=r(p,v?1:(b.max-b.min)*L/w(b.len,L)),!u(p)&&b.len<L&&!this.isRadial&&!this.isLog&&!v&&e&&f&&(D=!0,b.tickInterval/=4));k&&!a&&s(b.series,function(a){a.processData(b.min!==b.oldMin||b.max!==b.oldMax)});b.setAxisTranslation(!0);b.beforeSetTickPositions&&b.beforeSetTickPositions();b.postProcessTickInterval&&(b.tickInterval=b.postProcessTickInterval(b.tickInterval));b.pointRange&&(b.tickInterval=w(b.pointRange,b.tickInterval));!p&&b.tickInterval<
t&&(b.tickInterval=t);h||g||p||(b.tickInterval=fb(b.tickInterval,null,H.pow(10,K(H.log(b.tickInterval)/H.LN10)),r(d.allowDecimals,!(1<b.tickInterval&&5>b.tickInterval&&1E3<b.max&&9999>b.max))));b.minorTickInterval="auto"===d.minorTickInterval&&b.tickInterval?b.tickInterval/5:d.minorTickInterval;b.tickPositions=a=d.tickPositions?[].concat(d.tickPositions):m&&m.apply(b,[b.min,b.max]);a||(!b.ordinalPositions&&(b.max-b.min)/b.tickInterval>w(2*b.len,200)&&U(19,!0),a=h?b.getTimeTicks(b.normalizeTimeTickInterval(b.tickInterval,
d.units),b.min,b.max,d.startOfWeek,b.ordinalPositions,b.closestPointRange,!0):g?b.getLogTickPositions(b.tickInterval,b.min,b.max):b.getLinearTickPositions(b.tickInterval,b.min,b.max),D&&a.splice(1,a.length-2),b.tickPositions=a);l||(d=a[0],g=a[a.length-1],h=b.minPointOffset||0,e?b.min=d:b.min-h>d&&a.shift(),f?b.max=g:b.max+h<g&&a.pop(),0===a.length&&u(d)&&a.push((g+d)/2),1===a.length&&(e=1E13<P(b.max)?1:.001,b.min-=e,b.max+=e))},setMaxTicks:function(){var a=this.chart,b=a.maxTicks||{},c=this.tickPositions,
d=this._maxTicksKey=[this.coll,this.pos,this.len].join("-");!this.isLinked&&!this.isDatetimeAxis&&c&&c.length>(b[d]||0)&&!1!==this.options.alignTicks&&(b[d]=c.length);a.maxTicks=b},adjustTickAmount:function(){var a=this._maxTicksKey,b=this.tickPositions,c=this.chart.maxTicks;if(c&&c[a]&&!this.isDatetimeAxis&&!this.categories&&!this.isLinked&&!1!==this.options.alignTicks&&this.min!==v){var d=this.tickAmount,e=b.length;this.tickAmount=a=c[a];if(e<a){for(;b.length<a;)b.push(Z(b[b.length-1]+this.tickInterval));
this.transA*=(e-1)/(a-1);this.max=b[b.length-1]}u(d)&&a!==d&&(this.isDirty=!0)}},setScale:function(){var a=this.stacks,b,c,d,e;this.oldMin=this.min;this.oldMax=this.max;this.oldAxisLength=this.len;this.setAxisSize();e=this.len!==this.oldAxisLength;s(this.series,function(a){if(a.isDirtyData||a.isDirty||a.xAxis.isDirty)d=!0});if(e||d||this.isLinked||this.forceRedraw||this.userMin!==this.oldUserMin||this.userMax!==this.oldUserMax){if(!this.isXAxis)for(b in a)for(c in a[b])a[b][c].total=null,a[b][c].cum=
0;this.forceRedraw=!1;this.getSeriesExtremes();this.setTickPositions();this.oldUserMin=this.userMin;this.oldUserMax=this.userMax;this.isDirty||(this.isDirty=e||this.min!==this.oldMin||this.max!==this.oldMax)}else if(!this.isXAxis)for(b in this.oldStacks&&(a=this.stacks=this.oldStacks),a)for(c in a[b])a[b][c].cum=a[b][c].total;this.setMaxTicks()},setExtremes:function(a,b,c,d,e){var f=this,g=f.chart;c=r(c,!0);e=x(e,{min:a,max:b});R(f,"setExtremes",e,function(){f.userMin=a;f.userMax=b;f.eventArgs=e;
f.isDirtyExtremes=!0;c&&g.redraw(d)})},zoom:function(a,b){var c=this.dataMin,d=this.dataMax,e=this.options;this.allowZoomOutside||(u(c)&&a<=N(c,r(e.min,c))&&(a=v),u(d)&&b>=w(d,r(e.max,d))&&(b=v));this.displayBtn=a!==v||b!==v;this.setExtremes(a,b,!1,v,{trigger:"zoom"});return!0},setAxisSize:function(){var a=this.chart,b=this.options,c=b.offsetLeft||0,d=this.horiz,e=r(b.width,a.plotWidth-c+(b.offsetRight||0)),f=r(b.height,a.plotHeight),g=r(b.top,a.plotTop),b=r(b.left,a.plotLeft+c),c=/%$/;c.test(f)&&
(f=parseInt(f,10)/100*a.plotHeight);c.test(g)&&(g=parseInt(g,10)/100*a.plotHeight+a.plotTop);this.left=b;this.top=g;this.width=e;this.height=f;this.bottom=a.chartHeight-f-g;this.right=a.chartWidth-e-b;this.len=w(d?e:f,0);this.pos=d?b:g},getExtremes:function(){var a=this.isLog;return{min:a?Z(ca(this.min)):this.min,max:a?Z(ca(this.max)):this.max,dataMin:this.dataMin,dataMax:this.dataMax,userMin:this.userMin,userMax:this.userMax}},getThreshold:function(a){var b=this.isLog,c=b?ca(this.min):this.min,b=
b?ca(this.max):this.max;c>a||null===a?a=c:b<a&&(a=b);return this.translate(a,0,1,0,1)},autoLabelAlign:function(a){a=(r(a,0)-90*this.side+720)%360;return 15<a&&165>a?"right":195<a&&345>a?"left":"center"},getOffset:function(){var a=this,b=a.chart,c=b.renderer,d=a.options,e=a.tickPositions,f=a.ticks,g=a.horiz,h=a.side,k=b.inverted?[1,0,3,2][h]:h,l,m,n=0,q,p=0,t=d.title,L=d.labels,D=0,y=b.axisOffset,b=b.clipOffset,E=[-1,1,1,-1][h],I,x=1,z=r(L.maxStaggerLines,5),A,B,C,O,fa;a.hasData=l=a.hasVisibleSeries||
u(a.min)&&u(a.max)&&!!e;a.showAxis=m=l||r(d.showEmpty,!0);a.staggerLines=a.horiz&&L.staggerLines;a.axisGroup||(a.gridGroup=c.g("grid").attr({zIndex:d.gridZIndex||1}).add(),a.axisGroup=c.g("axis").attr({zIndex:d.zIndex||2}).add(),a.labelGroup=c.g("axis-labels").attr({zIndex:L.zIndex||7}).addClass("highcharts-"+a.coll.toLowerCase()+"-labels").add());if(l||a.isLinked){a.labelAlign=r(L.align||a.autoLabelAlign(L.rotation));s(e,function(b){f[b]?f[b].addLabel():f[b]=new ua(a,b)});if(a.horiz&&!a.staggerLines&&
z&&!L.rotation){for(l=a.reversed?[].concat(e).reverse():e;x<z;){A=[];B=!1;for(I=0;I<l.length;I++)C=l[I],O=(O=f[C].label&&f[C].label.getBBox())?O.width:0,fa=I%x,O&&(C=a.translate(C),A[fa]!==v&&C<A[fa]&&(B=!0),A[fa]=C+O);if(B)x++;else break}1<x&&(a.staggerLines=x)}s(e,function(b){if(0===h||2===h||{1:"left",3:"right"}[h]===a.labelAlign)D=w(f[b].getLabelSize(),D)});a.staggerLines&&(D*=a.staggerLines,a.labelOffset=D)}else for(I in f)f[I].destroy(),delete f[I];t&&t.text&&!1!==t.enabled&&(a.axisTitle||(a.axisTitle=
c.text(t.text,0,0,t.useHTML).attr({zIndex:7,rotation:t.rotation||0,align:t.textAlign||{low:"left",middle:"center",high:"right"}[t.align]}).addClass("highcharts-"+this.coll.toLowerCase()+"-title").css(t.style).add(a.axisGroup),a.axisTitle.isNew=!0),m&&(n=a.axisTitle.getBBox()[g?"height":"width"],q=t.offset,p=u(q)?0:r(t.margin,g?5:10)),a.axisTitle[m?"show":"hide"]());a.offset=E*r(d.offset,y[h]);c=2===h?a.tickBaseline:0;g=D+p+(D&&E*(g?r(L.y,a.tickBaseline+8):L.x)-c);a.axisTitleMargin=r(q,g);y[h]=w(y[h],
a.axisTitleMargin+n+E*a.offset,g);b[k]=w(b[k],2*K(d.lineWidth/2))},getLinePath:function(a){var b=this.chart,c=this.opposite,d=this.offset,e=this.horiz,f=this.left+(c?this.width:0)+d,d=b.chartHeight-this.bottom-(c?this.height:0)+d;c&&(a*=-1);return b.renderer.crispLine(["M",e?this.left:f,e?d:this.top,"L",e?b.chartWidth-this.right:f,e?d:b.chartHeight-this.bottom],a)},getTitlePosition:function(){var a=this.horiz,b=this.left,c=this.top,d=this.len,e=this.options.title,f=a?b:c,g=this.opposite,h=this.offset,
k=z(e.style.fontSize||12),d={low:f+(a?0:d),middle:f+d/2,high:f+(a?d:0)}[e.align],b=(a?c+this.height:b)+(a?1:-1)*(g?-1:1)*this.axisTitleMargin+(2===this.side?k:0);return{x:a?d:b+(g?this.width:0)+h+(e.x||0),y:a?b-(g?this.height:0)+h:d+(e.y||0)}},render:function(){var a=this,b=a.horiz,c=a.reversed,d=a.chart,e=d.renderer,f=a.options,g=a.isLog,h=a.isLinked,k=a.tickPositions,l,m=a.axisTitle,n=a.ticks,q=a.minorTicks,p=a.alternateBands,t=f.stackLabels,r=f.alternateGridColor,D=a.tickmarkOffset,w=f.lineWidth,
E=d.hasRendered&&u(a.oldMin)&&!isNaN(a.oldMin),y=a.hasData,x=a.showAxis,z,A=f.labels.overflow,B=a.justifyLabels=b&&!1!==A,C;a.labelEdge.length=0;a.justifyToPlot="justify"===A;s([n,q,p],function(a){for(var b in a)a[b].isActive=!1});if(y||h)a.minorTickInterval&&!a.categories&&s(a.getMinorTickPositions(),function(b){q[b]||(q[b]=new ua(a,b,"minor"));E&&q[b].isNew&&q[b].render(null,!0);q[b].render(null,!1,1)}),k.length&&(l=k.slice(),(b&&c||!b&&!c)&&l.reverse(),B&&(l=l.slice(1).concat([l[0]])),s(l,function(b,
c){B&&(c=c===l.length-1?0:c+1);if(!h||b>=a.min&&b<=a.max)n[b]||(n[b]=new ua(a,b)),E&&n[b].isNew&&n[b].render(c,!0,.1),n[b].render(c)}),D&&0===a.min&&(n[-1]||(n[-1]=new ua(a,-1,null,!0)),n[-1].render(-1))),r&&s(k,function(b,c){0===c%2&&b<a.max&&(p[b]||(p[b]=new T.PlotLineOrBand(a)),z=b+D,C=k[c+1]!==v?k[c+1]+D:a.max,p[b].options={from:g?ca(z):z,to:g?ca(C):C,color:r},p[b].render(),p[b].isActive=!0)}),a._addedPlotLB||(s((f.plotLines||[]).concat(f.plotBands||[]),function(b){a.addPlotBandOrLine(b)}),a._addedPlotLB=
!0);s([n,q,p],function(a){var b,c,e=[],f=W?W.duration||500:0,g=function(){for(c=e.length;c--;)a[e[c]]&&!a[e[c]].isActive&&(a[e[c]].destroy(),delete a[e[c]])};for(b in a)a[b].isActive||(a[b].render(b,!1,0),a[b].isActive=!1,e.push(b));a!==p&&d.hasRendered&&f?f&&setTimeout(g,f):g()});w&&(b=a.getLinePath(w),a.axisLine?a.axisLine.animate({d:b}):a.axisLine=e.path(b).attr({stroke:f.lineColor,"stroke-width":w,zIndex:7}).add(a.axisGroup),a.axisLine[x?"show":"hide"]());m&&x&&(m[m.isNew?"attr":"animate"](a.getTitlePosition()),
m.isNew=!1);t&&t.enabled&&a.renderStackTotals();a.isDirty=!1},redraw:function(){this.render();s(this.plotLinesAndBands,function(a){a.render()});s(this.series,function(a){a.isDirty=!0})},destroy:function(a){var b=this,c=b.stacks,d,e=b.plotLinesAndBands;a||X(b);for(d in c)Aa(c[d]),c[d]=null;s([b.ticks,b.minorTicks,b.alternateBands],function(a){Aa(a)});for(a=e.length;a--;)e[a].destroy();s("stackTotalGroup axisLine axisTitle axisGroup cross gridGroup labelGroup".split(" "),function(a){b[a]&&(b[a]=b[a].destroy())});
this.cross&&this.cross.destroy()},drawCrosshair:function(a,b){if(this.crosshair)if(!1===(u(b)||!r(this.crosshair.snap,!0)))this.hideCrosshair();else{var c,d=this.crosshair,e=d.animation;r(d.snap,!0)?u(b)&&(c=this.chart.inverted!=this.horiz?b.plotX:this.len-b.plotY):c=this.horiz?a.chartX-this.pos:this.len-a.chartY+this.pos;c=this.isRadial?this.getPlotLinePath(this.isXAxis?b.x:r(b.stackY,b.y)):this.getPlotLinePath(null,null,null,null,c);if(null===c)this.hideCrosshair();else if(this.cross)this.cross.attr({visibility:"visible"})[e?
"animate":"attr"]({d:c},e);else e={"stroke-width":d.width||1,stroke:d.color||"#C0C0C0",zIndex:d.zIndex||2},d.dashStyle&&(e.dashstyle=d.dashStyle),this.cross=this.chart.renderer.path(c).attr(e).add()}},hideCrosshair:function(){this.cross&&this.cross.hide()}};x(va.prototype,{getPlotBandPath:function(a,b){var c=this.getPlotLinePath(b),d=this.getPlotLinePath(a);d&&c?d.push(c[4],c[5],c[1],c[2]):d=null;return d},addPlotBand:function(a){return this.addPlotBandOrLine(a,"plotBands")},addPlotLine:function(a){return this.addPlotBandOrLine(a,
"plotLines")},addPlotBandOrLine:function(a,b){var c=(new T.PlotLineOrBand(this,a)).render(),d=this.userOptions;c&&(b&&(d[b]=d[b]||[],d[b].push(a)),this.plotLinesAndBands.push(c));return c},removePlotBandOrLine:function(a){for(var b=this.plotLinesAndBands,c=this.options,d=this.userOptions,e=b.length;e--;)b[e].id===a&&b[e].destroy();s([c.plotLines||[],d.plotLines||[],c.plotBands||[],d.plotBands||[]],function(b){for(e=b.length;e--;)b[e].id===a&&ha(b,b[e])})}});va.prototype.getTimeTicks=function(a,b,
c,d){var e=[],f={},g=J.global.useUTC,h,k=new sa(b-ta),l=a.unitRange,m=a.count;if(u(b)){l>=A.second&&(k.setMilliseconds(0),k.setSeconds(l>=A.minute?0:m*K(k.getSeconds()/m)));if(l>=A.minute)k[hb](l>=A.hour?0:m*K(k[Wa]()/m));if(l>=A.hour)k[ib](l>=A.day?0:m*K(k[Xa]()/m));if(l>=A.day)k[Za](l>=A.month?1:m*K(k[Ba]()/m));l>=A.month&&(k[jb](l>=A.year?0:m*K(k[Ma]()/m)),h=k[Na]());if(l>=A.year)k[kb](h-h%m);if(l===A.week)k[Za](k[Ba]()-k[Ya]()+r(d,1));b=1;ta&&(k=new sa(k.getTime()+ta));h=k[Na]();d=k.getTime();
for(var n=k[Ma](),q=k[Ba](),p=(A.day+(g?ta:6E4*k.getTimezoneOffset()))%A.day;d<c;)e.push(d),d=l===A.year?La(h+b*m,0):l===A.month?La(h,n+b*m):g||l!==A.day&&l!==A.week?d+l*m:La(h,n,q+b*m*(l===A.day?1:7)),b++;e.push(d);s(cb(e,function(a){return l<=A.hour&&a%A.day===p}),function(a){f[a]="day"})}e.info=x(a,{higherRanks:f,totalRange:l*m});return e};va.prototype.normalizeTimeTickInterval=function(a,b){var c=b||[["millisecond",[1,2,5,10,20,25,50,100,200,500]],["second",[1,2,5,10,15,30]],["minute",[1,2,5,
10,15,30]],["hour",[1,2,3,4,6,8,12]],["day",[1,2]],["week",[1,2]],["month",[1,2,3,4,6]],["year",null]],d=c[c.length-1],e=A[d[0]],f=d[1],g;for(g=0;g<c.length&&!(d=c[g],e=A[d[0]],f=d[1],c[g+1]&&a<=(e*f[f.length-1]+A[c[g+1][0]])/2);g++);e===A.year&&a<5*e&&(f=[1,2,5]);c=fb(a/e,f,"year"===d[0]?w(H.pow(10,K(H.log(a/e)/H.LN10)),1):1);return{unitRange:e,count:c,unitName:d[0]}};var eb=T.Legend=function(a,b){this.init(a,b)};eb.prototype={init:function(a,b){var c=this,d=b.itemStyle,e=r(b.padding,8),f=b.itemMarginTop||
0;this.options=b;b.enabled&&(c.itemStyle=d,c.itemHiddenStyle=C(d,b.itemHiddenStyle),c.itemMarginTop=f,c.padding=e,c.initialItemX=e,c.initialItemY=e-5,c.maxItemWidth=0,c.chart=a,c.itemHeight=0,c.lastLineHeight=0,c.symbolWidth=r(b.symbolWidth,16),c.pages=[],c.render(),Q(c.chart,"endResize",function(){c.positionCheckboxes()}))},colorizeItem:function(a,b){var c=this.options,d=a.legendItem,e=a.legendLine,f=a.legendSymbol,g=this.itemHiddenStyle.color,c=b?c.itemStyle.color:g,h=b?a.legendColor||a.color||
"#CCC":g,g=a.options&&a.options.marker,k={fill:h},l;d&&d.css({fill:c,color:c});e&&e.attr({stroke:h});if(f){if(g&&f.isMarker)for(l in k.stroke=h,g=a.convertAttribs(g),g)d=g[l],d!==v&&(k[l]=d);f.attr(k)}},positionItem:function(a){var b=this.options,c=b.symbolPadding,b=!b.rtl,d=a._legendItemPos,e=d[0],d=d[1],f=a.checkbox;a.legendGroup&&a.legendGroup.translate(b?e:this.legendWidth-e-2*c-4,d);f&&(f.x=e,f.y=d)},destroyItem:function(a){var b=a.checkbox;s(["legendItem","legendLine","legendSymbol","legendGroup"],
function(b){a[b]&&(a[b]=a[b].destroy())});b&&Ja(a.checkbox)},destroy:function(){var a=this.group,b=this.box;b&&(this.box=b.destroy());a&&(this.group=a.destroy())},positionCheckboxes:function(a){var b=this.group.alignAttr,c,d=this.clipHeight||this.legendHeight;b&&(c=b.translateY,s(this.allItems,function(e){var f=e.checkbox,g;f&&(g=c+f.y+(a||0)+3,V(f,{left:b.translateX+e.checkboxOffset+f.x-20+"px",top:g+"px",display:g>c-6&&g<c+d-6?"":"none"}))}))},renderTitle:function(){var a=this.padding,b=this.options.title,
c=0;b.text&&(this.title||(this.title=this.chart.renderer.label(b.text,a-3,a-4,null,null,null,null,null,"legend-title").attr({zIndex:1}).css(b.style).add(this.group)),a=this.title.getBBox(),c=a.height,this.offsetWidth=a.width,this.contentGroup.attr({translateY:c}));this.titleHeight=c},renderItem:function(a){var b=this.chart,c=b.renderer,d=this.options,e="horizontal"===d.layout,f=this.symbolWidth,g=d.symbolPadding,h=this.itemStyle,k=this.itemHiddenStyle,l=this.padding,m=e?r(d.itemDistance,20):0,n=!d.rtl,
q=d.width,p=d.itemMarginBottom||0,t=this.itemMarginTop,s=this.initialItemX,u=a.legendItem,v=a.series&&a.series.drawLegendSymbol?a.series:a,E=v.options,E=this.createCheckboxForItem&&E&&E.showCheckbox,x=d.useHTML;u||(a.legendGroup=c.g("legend-item").attr({zIndex:1}).add(this.scrollGroup),a.legendItem=u=c.text(d.labelFormat?Ha(d.labelFormat,a):d.labelFormatter.call(a),n?f+g:-g,this.baseline||0,x).css(C(a.visible?h:k)).attr({align:n?"left":"right",zIndex:2}).add(a.legendGroup),this.baseline||(this.baseline=
c.fontMetrics(h.fontSize,u).f+3+t,u.attr("y",this.baseline)),v.drawLegendSymbol(this,a),this.setItemEvents&&this.setItemEvents(a,u,x,h,k),this.colorizeItem(a,a.visible),E&&this.createCheckboxForItem(a));c=u.getBBox();f=a.checkboxOffset=d.itemWidth||a.legendItemWidth||f+g+c.width+m+(E?20:0);this.itemHeight=g=y(a.legendItemHeight||c.height);e&&this.itemX-s+f>(q||b.chartWidth-2*l-s-d.x)&&(this.itemX=s,this.itemY+=t+this.lastLineHeight+p,this.lastLineHeight=0);this.maxItemWidth=w(this.maxItemWidth,f);
this.lastItemY=t+this.itemY+p;this.lastLineHeight=w(g,this.lastLineHeight);a._legendItemPos=[this.itemX,this.itemY];e?this.itemX+=f:(this.itemY+=t+g+p,this.lastLineHeight=g);this.offsetWidth=q||w((e?this.itemX-s-m:f)+l,this.offsetWidth)},getAllItems:function(){var a=[];s(this.chart.series,function(b){var c=b.options;r(c.showInLegend,u(c.linkedTo)?!1:v,!0)&&(a=a.concat(b.legendItems||("point"===c.legendType?b.data:b)))});return a},render:function(){var a=this,b=a.chart,c=b.renderer,d=a.group,e,f,g,
h,k=a.box,l=a.options,m=a.padding,n=l.borderWidth,q=l.backgroundColor;a.itemX=a.initialItemX;a.itemY=a.initialItemY;a.offsetWidth=0;a.lastItemY=0;d||(a.group=d=c.g("legend").attr({zIndex:7}).add(),a.contentGroup=c.g().attr({zIndex:1}).add(d),a.scrollGroup=c.g().add(a.contentGroup));a.renderTitle();e=a.getAllItems();Va(e,function(a,b){return(a.options&&a.options.legendIndex||0)-(b.options&&b.options.legendIndex||0)});l.reversed&&e.reverse();a.allItems=e;a.display=f=!!e.length;s(e,function(b){a.renderItem(b)});
g=l.width||a.offsetWidth;h=a.lastItemY+a.lastLineHeight+a.titleHeight;h=a.handleOverflow(h);if(n||q)g+=m,h+=m,k?0<g&&0<h&&(k[k.isNew?"attr":"animate"](k.crisp({width:g,height:h})),k.isNew=!1):(a.box=k=c.rect(0,0,g,h,l.borderRadius,n||0).attr({stroke:l.borderColor,"stroke-width":n||0,fill:q||"none"}).add(d).shadow(l.shadow),k.isNew=!0),k[f?"show":"hide"]();a.legendWidth=g;a.legendHeight=h;s(e,function(b){a.positionItem(b)});f&&d.align(x({width:g,height:h},l),!0,"spacingBox");b.isResizing||this.positionCheckboxes()},
handleOverflow:function(a){var b=this,c=this.chart,d=c.renderer,e=this.options,f=e.y,f=c.spacingBox.height+("top"===e.verticalAlign?-f:f)-this.padding,g=e.maxHeight,h,k=this.clipRect,l=e.navigation,m=r(l.animation,!0),n=l.arrowSize||12,q=this.nav,p=this.pages,t,u=this.allItems;"horizontal"===e.layout&&(f/=2);g&&(f=N(f,g));p.length=0;a>f&&!e.useHTML?(this.clipHeight=h=w(f-20-this.titleHeight-this.padding,0),this.currentPage=r(this.currentPage,1),this.fullHeight=a,s(u,function(a,b){var c=a._legendItemPos[1],
d=y(a.legendItem.getBBox().height),e=p.length;if(!e||c-p[e-1]>h&&(t||c)!==p[e-1])p.push(t||c),e++;b===u.length-1&&c+d-p[e-1]>h&&p.push(c);c!==t&&(t=c)}),k||(k=b.clipRect=d.clipRect(0,this.padding,9999,0),b.contentGroup.clip(k)),k.attr({height:h}),q||(this.nav=q=d.g().attr({zIndex:1}).add(this.group),this.up=d.symbol("triangle",0,0,n,n).on("click",function(){b.scroll(-1,m)}).add(q),this.pager=d.text("",15,10).css(l.style).add(q),this.down=d.symbol("triangle-down",0,0,n,n).on("click",function(){b.scroll(1,
m)}).add(q)),b.scroll(0),a=f):q&&(k.attr({height:c.chartHeight}),q.hide(),this.scrollGroup.attr({translateY:1}),this.clipHeight=0);return a},scroll:function(a,b){var c=this.pages,d=c.length,e=this.currentPage+a,f=this.clipHeight,g=this.options.navigation,h=g.activeColor,g=g.inactiveColor,k=this.pager,l=this.padding;e>d&&(e=d);0<e&&(b!==v&&(W=r(b,this.chart.animation)),this.nav.attr({translateX:l,translateY:f+this.padding+7+this.titleHeight,visibility:"visible"}),this.up.attr({fill:1===e?g:h}).css({cursor:1===
e?"default":"pointer"}),k.attr({text:e+"/"+d}),this.down.attr({x:18+this.pager.getBBox().width,fill:e===d?g:h}).css({cursor:e===d?"default":"pointer"}),c=-c[e-1]+this.initialItemY,this.scrollGroup.animate({translateY:c}),this.currentPage=e,this.positionCheckboxes(c))}};var ub=T.LegendSymbolMixin={drawRectangle:function(a,b){var c=a.options.symbolHeight||12;b.legendSymbol=this.chart.renderer.rect(0,a.baseline-5-c/2,a.symbolWidth,c,a.options.symbolRadius||0).attr({zIndex:3}).add(b.legendGroup)},drawLineMarker:function(a){var b=
this.options,c=b.marker,d;d=a.symbolWidth;var e=this.chart.renderer,f=this.legendGroup;a=a.baseline-y(.3*e.fontMetrics(a.options.itemStyle.fontSize,this.legendItem).b);var g;b.lineWidth&&(g={"stroke-width":b.lineWidth},b.dashStyle&&(g.dashstyle=b.dashStyle),this.legendLine=e.path(["M",0,a,"L",d,a]).attr(g).add(f));c&&!1!==c.enabled&&(b=c.radius,this.legendSymbol=d=e.symbol(this.symbol,d/2-b,a-b,2*b,2*b).add(f),d.isMarker=!0)}};(/Trident\/7\.0/.test(ma)||Pa)&&Ua(eb.prototype,"positionItem",function(a,
b){var c=this,d=function(){b._legendItemPos&&a.call(c,b)};d();setTimeout(d)});$a.prototype={init:function(a,b){var c,d=a.series;a.series=null;c=C(J,a);c.series=a.series=d;this.userOptions=a;d=c.chart;this.margin=this.splashArray("margin",d);this.spacing=this.splashArray("spacing",d);var e=d.events;this.bounds={h:{},v:{}};this.callback=b;this.isResizing=0;this.options=c;this.axes=[];this.series=[];this.hasCartesianSeries=d.showAxes;var f=this,g;f.index=ea.length;ea.push(f);qb++;!1!==d.reflow&&Q(f,
"load",function(){f.initReflow()});if(e)for(g in e)Q(f,g,e[g]);f.xAxis=[];f.yAxis=[];f.animation=$?!1:r(d.animation,!0);f.pointCount=f.colorCounter=f.symbolCounter=0;f.firstRender()},initSeries:function(a){var b=this.options.chart;(b=na[a.type||b.type||b.defaultSeriesType])||U(17,!0);b=new b;b.init(this,a);return b},isInsidePlot:function(a,b,c){var d=c?b:a;a=c?a:b;return 0<=d&&d<=this.plotWidth&&0<=a&&a<=this.plotHeight},adjustTickAmounts:function(){!1!==this.options.chart.alignTicks&&s(this.axes,
function(a){a.adjustTickAmount()});this.maxTicks=null},redraw:function(a){var b=this.axes,c=this.series,d=this.pointer,e=this.legend,f=this.isDirtyLegend,g,h,k=this.hasCartesianSeries,l=this.isDirtyBox,m=c.length,n=m,q=this.renderer,p=q.isHidden(),t=[];W=r(a,this.animation);p&&this.cloneRenderTo();for(this.layOutTitles();n--;)if(a=c[n],a.options.stacking&&(g=!0,a.isDirty)){h=!0;break}if(h)for(n=m;n--;)a=c[n],a.options.stacking&&(a.isDirty=!0);s(c,function(a){a.isDirty&&"point"===a.options.legendType&&
(f=!0)});f&&e.options.enabled&&(e.render(),this.isDirtyLegend=!1);g&&this.getStacks();k&&(this.isResizing||(this.maxTicks=null,s(b,function(a){a.setScale()})),this.adjustTickAmounts());this.getMargins();k&&(s(b,function(a){a.isDirty&&(l=!0)}),s(b,function(a){a.isDirtyExtremes&&(a.isDirtyExtremes=!1,t.push(function(){R(a,"afterSetExtremes",x(a.eventArgs,a.getExtremes()));delete a.eventArgs}));(l||g)&&a.redraw()}));l&&this.drawChartBox();s(c,function(a){a.isDirty&&a.visible&&(!a.isCartesian||a.xAxis)&&
a.redraw()});d&&d.reset(!0);q.draw();R(this,"redraw");p&&this.cloneRenderTo(!0);s(t,function(a){a.call()})},get:function(a){var b=this.axes,c=this.series,d,e;for(d=0;d<b.length;d++)if(b[d].options.id===a)return b[d];for(d=0;d<c.length;d++)if(c[d].options.id===a)return c[d];for(d=0;d<c.length;d++)for(e=c[d].points||[],b=0;b<e.length;b++)if(e[b].id===a)return e[b];return null},getAxes:function(){var a=this,b=this.options,c=b.xAxis=ya(b.xAxis||{}),b=b.yAxis=ya(b.yAxis||{});s(c,function(a,b){a.index=
b;a.isX=!0});s(b,function(a,b){a.index=b});c=c.concat(b);s(c,function(b){new va(a,b)});a.adjustTickAmounts()},getSelectedPoints:function(){var a=[];s(this.series,function(b){a=a.concat(cb(b.points||[],function(a){return a.selected}))});return a},getSelectedSeries:function(){return cb(this.series,function(a){return a.selected})},getStacks:function(){var a=this;s(a.yAxis,function(a){a.stacks&&a.hasVisibleSeries&&(a.oldStacks=a.stacks)});s(a.series,function(b){!b.options.stacking||!0!==b.visible&&!1!==
a.options.chart.ignoreHiddenSeries||(b.stackKey=b.type+r(b.options.stack,""))})},setTitle:function(a,b,c){var d=this,e=d.options,f;f=e.title=C(e.title,a);e=e.subtitle=C(e.subtitle,b);s([["title",a,f],["subtitle",b,e]],function(a){var b=a[0],c=d[b],e=a[1];a=a[2];c&&e&&(d[b]=c=c.destroy());a&&a.text&&!c&&(d[b]=d.renderer.text(a.text,0,0,a.useHTML).attr({align:a.align,"class":"highcharts-"+b,zIndex:a.zIndex||4}).css(a.style).add())});d.layOutTitles(c)},layOutTitles:function(a){var b=0,c=this.title,d=
this.subtitle,e=this.options,f=e.title,e=e.subtitle,g=this.renderer,h=this.spacingBox.width-44;c&&(c.css({width:(f.width||h)+"px"}).align(x({y:g.fontMetrics(f.style.fontSize,c).b-3},f),!1,"spacingBox"),f.floating||f.verticalAlign||(b=c.getBBox().height));d&&(d.css({width:(e.width||h)+"px"}).align(x({y:b+(f.margin-13)+g.fontMetrics(f.style.fontSize,d).b},e),!1,"spacingBox"),e.floating||e.verticalAlign||(b=la(b+d.getBBox().height)));c=this.titleOffset!==b;this.titleOffset=b;!this.isDirtyBox&&c&&(this.isDirtyBox=
c,this.hasRendered&&r(a,!0)&&this.isDirtyBox&&this.redraw())},getChartSize:function(){var a=this.options.chart,b=a.width,a=a.height,c=this.renderToClone||this.renderTo;u(b)||(this.containerWidth=Ra(c,"width"));u(a)||(this.containerHeight=Ra(c,"height"));this.chartWidth=w(0,b||this.containerWidth||600);this.chartHeight=w(0,r(a,19<this.containerHeight?this.containerHeight:400))},cloneRenderTo:function(a){var b=this.renderToClone,c=this.container;a?b&&(this.renderTo.appendChild(c),Ja(b),delete this.renderToClone):
(c&&c.parentNode===this.renderTo&&this.renderTo.removeChild(c),this.renderToClone=b=this.renderTo.cloneNode(0),V(b,{position:"absolute",top:"-9999px",display:"block"}),b.style.setProperty&&b.style.setProperty("display","block","important"),B.body.appendChild(b),c&&b.appendChild(c))},getContainer:function(){var a,b=this.options.chart,c,d,e;this.renderTo=a=b.renderTo;e="highcharts-"+ab++;ga(a)&&(this.renderTo=a=B.getElementById(a));a||U(13,!0);c=z(G(a,"data-highcharts-chart"));!isNaN(c)&&ea[c]&&ea[c].hasRendered&&
ea[c].destroy();G(a,"data-highcharts-chart",this.index);a.innerHTML="";b.skipClone||a.offsetWidth||this.cloneRenderTo();this.getChartSize();c=this.chartWidth;d=this.chartHeight;this.container=a=za("div",{className:"highcharts-container"+(b.className?" "+b.className:""),id:e},x({position:"relative",overflow:"hidden",width:c+"px",height:d+"px",textAlign:"left",lineHeight:"normal",zIndex:0,"-webkit-tap-highlight-color":"rgba(0,0,0,0)"},b.style),this.renderToClone||a);this._cursor=a.style.cursor;this.renderer=
b.forExport?new Ea(a,c,d,b.style,!0):new Ea(a,c,d,b.style);$&&this.renderer.create(this,a,c,d)},getMargins:function(){var a=this.spacing,b,c=this.legend,d=this.margin,e=this.options.legend,f=r(e.margin,20),g=e.x,h=e.y,k=e.align,l=e.verticalAlign,m=this.titleOffset;this.resetMargins();b=this.axisOffset;m&&!u(d[0])&&(this.plotTop=w(this.plotTop,m+this.options.title.margin+a[0]));c.display&&!e.floating&&("right"===k?u(d[1])||(this.marginRight=w(this.marginRight,c.legendWidth-g+f+a[1])):"left"===k?u(d[3])||
(this.plotLeft=w(this.plotLeft,c.legendWidth+g+f+a[3])):"top"===l?u(d[0])||(this.plotTop=w(this.plotTop,c.legendHeight+h+f+a[0])):"bottom"!==l||u(d[2])||(this.marginBottom=w(this.marginBottom,c.legendHeight-h+f+a[2])));this.extraBottomMargin&&(this.marginBottom+=this.extraBottomMargin);this.extraTopMargin&&(this.plotTop+=this.extraTopMargin);this.hasCartesianSeries&&s(this.axes,function(a){a.getOffset()});u(d[3])||(this.plotLeft+=b[3]);u(d[0])||(this.plotTop+=b[0]);u(d[2])||(this.marginBottom+=b[2]);
u(d[1])||(this.marginRight+=b[1]);this.setChartSize()},reflow:function(a){var b=this,c=b.options.chart,d=b.renderTo,e=c.width||Ra(d,"width"),f=c.height||Ra(d,"height"),c=a?a.target:F,d=function(){b.container&&(b.setSize(e,f,!1),b.hasUserSize=null)};if(!b.hasUserSize&&e&&f&&(c===F||c===B)){if(e!==b.containerWidth||f!==b.containerHeight)clearTimeout(b.reflowTimeout),a?b.reflowTimeout=setTimeout(d,100):d();b.containerWidth=e;b.containerHeight=f}},initReflow:function(){var a=this,b=function(b){a.reflow(b)};
Q(F,"resize",b);Q(a,"destroy",function(){X(F,"resize",b)})},setSize:function(a,b,c){var d=this,e,f,g;d.isResizing+=1;g=function(){d&&R(d,"endResize",null,function(){d.isResizing-=1})};W=r(c,d.animation);d.oldChartHeight=d.chartHeight;d.oldChartWidth=d.chartWidth;u(a)&&(d.chartWidth=e=w(0,y(a)),d.hasUserSize=!!e);u(b)&&(d.chartHeight=f=w(0,y(b)));(W?sb:V)(d.container,{width:e+"px",height:f+"px"},W);d.setChartSize(!0);d.renderer.setSize(e,f,c);d.maxTicks=null;s(d.axes,function(a){a.isDirty=!0;a.setScale()});
s(d.series,function(a){a.isDirty=!0});d.isDirtyLegend=!0;d.isDirtyBox=!0;d.layOutTitles();d.getMargins();d.redraw(c);d.oldChartHeight=null;R(d,"resize");!1===W?g():setTimeout(g,W&&W.duration||500)},setChartSize:function(a){var b=this.inverted,c=this.renderer,d=this.chartWidth,e=this.chartHeight,f=this.options.chart,g=this.spacing,h=this.clipOffset,k,l,m,n;this.plotLeft=k=y(this.plotLeft);this.plotTop=l=y(this.plotTop);this.plotWidth=m=w(0,y(d-k-this.marginRight));this.plotHeight=n=w(0,y(e-l-this.marginBottom));
this.plotSizeX=b?n:m;this.plotSizeY=b?m:n;this.plotBorderWidth=f.plotBorderWidth||0;this.spacingBox=c.spacingBox={x:g[3],y:g[0],width:d-g[3]-g[1],height:e-g[0]-g[2]};this.plotBox=c.plotBox={x:k,y:l,width:m,height:n};d=2*K(this.plotBorderWidth/2);b=la(w(d,h[3])/2);c=la(w(d,h[0])/2);this.clipBox={x:b,y:c,width:K(this.plotSizeX-w(d,h[1])/2-b),height:w(0,K(this.plotSizeY-w(d,h[2])/2-c))};a||s(this.axes,function(a){a.setAxisSize();a.setAxisTranslation()})},resetMargins:function(){var a=this.spacing,b=
this.margin;this.plotTop=r(b[0],a[0]);this.marginRight=r(b[1],a[1]);this.marginBottom=r(b[2],a[2]);this.plotLeft=r(b[3],a[3]);this.axisOffset=[0,0,0,0];this.clipOffset=[0,0,0,0]},drawChartBox:function(){var a=this.options.chart,b=this.renderer,c=this.chartWidth,d=this.chartHeight,e=this.chartBackground,f=this.plotBackground,g=this.plotBorder,h=this.plotBGImage,k=a.borderWidth||0,l=a.backgroundColor,m=a.plotBackgroundColor,n=a.plotBackgroundImage,q=a.plotBorderWidth||0,p,t=this.plotLeft,r=this.plotTop,
s=this.plotWidth,u=this.plotHeight,v=this.plotBox,w=this.clipRect,x=this.clipBox;p=k+(a.shadow?8:0);if(k||l)e?e.animate(e.crisp({width:c-p,height:d-p})):(e={fill:l||"none"},k&&(e.stroke=a.borderColor,e["stroke-width"]=k),this.chartBackground=b.rect(p/2,p/2,c-p,d-p,a.borderRadius,k).attr(e).addClass("highcharts-background").add().shadow(a.shadow));m&&(f?f.animate(v):this.plotBackground=b.rect(t,r,s,u,0).attr({fill:m}).add().shadow(a.plotShadow));n&&(h?h.animate(v):this.plotBGImage=b.image(n,t,r,s,
u).add());w?w.animate({width:x.width,height:x.height}):this.clipRect=b.clipRect(x);q&&(g?g.animate(g.crisp({x:t,y:r,width:s,height:u,strokeWidth:-q})):this.plotBorder=b.rect(t,r,s,u,0,-q).attr({stroke:a.plotBorderColor,"stroke-width":q,fill:"none",zIndex:1}).add());this.isDirtyBox=!1},propFromSeries:function(){var a=this,b=a.options.chart,c,d=a.options.series,e,f;s(["inverted","angular","polar"],function(g){c=na[b.type||b.defaultSeriesType];f=a[g]||b[g]||c&&c.prototype[g];for(e=d&&d.length;!f&&e--;)(c=
na[d[e].type])&&c.prototype[g]&&(f=!0);a[g]=f})},linkSeries:function(){var a=this,b=a.series;s(b,function(a){a.linkedSeries.length=0});s(b,function(b){var d=b.options.linkedTo;ga(d)&&(d=":previous"===d?a.series[b.index-1]:a.get(d))&&(d.linkedSeries.push(b),b.linkedParent=d)})},renderSeries:function(){s(this.series,function(a){a.translate();a.setTooltipPoints&&a.setTooltipPoints();a.render()})},renderLabels:function(){var a=this,b=a.options.labels;b.items&&s(b.items,function(c){var d=x(b.style,c.style),
e=z(d.left)+a.plotLeft,f=z(d.top)+a.plotTop+12;delete d.left;delete d.top;a.renderer.text(c.html,e,f).attr({zIndex:2}).css(d).add()})},render:function(){var a=this.axes,b=this.renderer,c=this.options;this.setTitle();this.legend=new eb(this,c.legend);this.getStacks();s(a,function(a){a.setScale()});this.getMargins();this.maxTicks=null;s(a,function(a){a.setTickPositions(!0);a.setMaxTicks()});this.adjustTickAmounts();this.getMargins();this.drawChartBox();this.hasCartesianSeries&&s(a,function(a){a.render()});
this.seriesGroup||(this.seriesGroup=b.g("series-group").attr({zIndex:3}).add());this.renderSeries();this.renderLabels();this.showCredits(c.credits);this.hasRendered=!0},showCredits:function(a){a.enabled&&!this.credits&&(this.credits=this.renderer.text(a.text,0,0).on("click",function(){a.href&&(location.href=a.href)}).attr({align:a.position.align,zIndex:8}).css(a.style).add().align(a.position))},destroy:function(){var a=this,b=a.axes,c=a.series,d=a.container,e,f=d&&d.parentNode;R(a,"destroy");ea[a.index]=
v;qb--;a.renderTo.removeAttribute("data-highcharts-chart");X(a);for(e=b.length;e--;)b[e]=b[e].destroy();for(e=c.length;e--;)c[e]=c[e].destroy();s("title subtitle chartBackground plotBackground plotBGImage plotBorder seriesGroup clipRect credits pointer scroller rangeSelector legend resetZoomButton tooltip renderer".split(" "),function(b){var c=a[b];c&&c.destroy&&(a[b]=c.destroy())});d&&(d.innerHTML="",X(d),f&&Ja(d));for(e in a)delete a[e]},isReadyToRender:function(){var a=this;return!S&&F==F.top&&
"complete"!==B.readyState||$&&!F.canvg?($?CanVGController.push(function(){a.firstRender()},a.options.global.canvasToolsURL):B.attachEvent("onreadystatechange",function(){B.detachEvent("onreadystatechange",a.firstRender);"complete"===B.readyState&&a.firstRender()}),!1):!0},firstRender:function(){var a=this,b=a.options,c=a.callback;a.isReadyToRender()&&(a.getContainer(),R(a,"init"),a.resetMargins(),a.setChartSize(),a.propFromSeries(),a.getAxes(),s(b.series||[],function(b){a.initSeries(b)}),a.linkSeries(),
R(a,"beforeRender"),T.Pointer&&(a.pointer=new Pointer(a,b)),a.render(),a.renderer.draw(),c&&c.apply(a,[a]),s(a.callbacks,function(b){b.apply(a,[a])}),a.cloneRenderTo(!0),R(a,"load"))},splashArray:function(a,b){var c=b[a],c=aa(c)?c:[c,c,c,c];return[r(b[a+"Top"],c[0]),r(b[a+"Right"],c[1]),r(b[a+"Bottom"],c[2]),r(b[a+"Left"],c[3])]}};$a.prototype.callbacks=[];var Ta=function(){};Ta.prototype={init:function(a,b,c){this.series=a;this.applyOptions(b,c);this.pointAttr={};a.options.colorByPoint&&(b=a.options.colors||
a.chart.options.colors,this.color=this.color||b[a.colorCounter++],a.colorCounter===b.length&&(a.colorCounter=0));a.chart.pointCount++;return this},applyOptions:function(a,b){var c=this.series,d=c.options.pointValKey||c.pointValKey;a=Ta.prototype.optionsToObject.call(this,a);x(this,a);this.options=this.options?x(this.options,a):a;d&&(this.y=this[d]);this.x===v&&c&&(this.x=b===v?c.autoIncrement():b);return this},optionsToObject:function(a){var b={},c=this.series,d=c.pointArrayMap||["y"],e=d.length,
f=0,g=0;if("number"===typeof a||null===a)b[d[0]]=a;else if(xa(a))for(a.length>e&&(c=typeof a[0],"string"===c?b.name=a[0]:"number"===c&&(b.x=a[0]),f++);g<e;)b[d[g++]]=a[f++];else"object"===typeof a&&(b=a,a.dataLabels&&(c._hasPointLabels=!0),a.marker&&(c._hasPointMarkers=!0));return b},destroy:function(){var a=this.series.chart,b=a.hoverPoints,c;a.pointCount--;b&&(this.setState(),ha(b,this),b.length||(a.hoverPoints=null));if(this===a.hoverPoint)this.onMouseOut();if(this.graphic||this.dataLabel)X(this),
this.destroyElements();this.legendItem&&a.legend.destroyItem(this);for(c in this)this[c]=null},destroyElements:function(){for(var a="graphic dataLabel dataLabelUpper group connector shadowGroup".split(" "),b,c=6;c--;)b=a[c],this[b]&&(this[b]=this[b].destroy())},getLabelConfig:function(){return{x:this.category,y:this.y,key:this.name||this.category,series:this.series,point:this,percentage:this.percentage,total:this.total||this.stackTotal}},tooltipFormatter:function(a){var b=this.series,c=b.tooltipOptions,
d=r(c.valueDecimals,""),e=c.valuePrefix||"",f=c.valueSuffix||"";s(b.pointArrayMap||["y"],function(b){b="{point."+b;if(e||f)a=a.replace(b+"}",e+b+"}"+f);a=a.replace(b+"}",b+":,."+d+"f}")});return Ha(a,{point:this,series:this.series})},firePointEvent:function(a,b,c){var d=this,e=this.series.options;(e.point.events[a]||d.options&&d.options.events&&d.options.events[a])&&this.importEvents();"click"===a&&e.allowPointSelect&&(c=function(a){d.select(null,a.ctrlKey||a.metaKey||a.shiftKey)});R(this,a,b,c)}};
var pa=function(){};pa.prototype={isCartesian:!0,type:"line",pointClass:Ta,sorted:!0,requireSorting:!0,pointAttrToOptions:{stroke:"lineColor","stroke-width":"lineWidth",fill:"fillColor",r:"radius"},axisTypes:["xAxis","yAxis"],colorCounter:0,parallelArrays:["x","y"],init:function(a,b){var c=this,d,e,f=a.series,g=function(a,b){return r(a.options.index,a._i)-r(b.options.index,b._i)};c.chart=a;c.options=b=c.setOptions(b);c.linkedSeries=[];c.bindAxes();x(c,{name:b.name,state:"",pointAttr:{},visible:!1!==
b.visible,selected:!0===b.selected});$&&(b.animation=!1);e=b.events;for(d in e)Q(c,d,e[d]);if(e&&e.click||b.point&&b.point.events&&b.point.events.click||b.allowPointSelect)a.runTrackerClick=!0;c.getColor();c.getSymbol();s(c.parallelArrays,function(a){c[a+"Data"]=[]});c.setData(b.data,!1);c.isCartesian&&(a.hasCartesianSeries=!0);f.push(c);c._i=f.length-1;Va(f,g);this.yAxis&&Va(this.yAxis.series,g);s(f,function(a,b){a.index=b;a.name=a.name||"Series "+(b+1)})},bindAxes:function(){var a=this,b=a.options,
c=a.chart,d;s(a.axisTypes||[],function(e){s(c[e],function(c){d=c.options;if(b[e]===d.index||b[e]!==v&&b[e]===d.id||b[e]===v&&0===d.index)c.series.push(a),a[e]=c,c.isDirty=!0});a[e]||a.optionalAxis===e||U(18,!0)})},updateParallelArrays:function(a,b){var c=a.series,d=arguments;s(c.parallelArrays,"number"===typeof b?function(d){var f="y"===d&&c.toYData?c.toYData(a):a[d];c[d+"Data"][b]=f}:function(a){Array.prototype[b].apply(c[a+"Data"],Array.prototype.slice.call(d,2))})},autoIncrement:function(){var a=
this.options,b=this.xIncrement,b=r(b,a.pointStart,0);this.pointInterval=r(this.pointInterval,a.pointInterval,1);this.xIncrement=b+this.pointInterval;return b},getSegments:function(){var a=-1,b=[],c,d=this.points,e=d.length;if(e)if(this.options.connectNulls){for(c=e;c--;)null===d[c].y&&d.splice(c,1);d.length&&(b=[d])}else s(d,function(c,g){null===c.y?(g>a+1&&b.push(d.slice(a+1,g)),a=g):g===e-1&&b.push(d.slice(a+1,g+1))});this.segments=b},setOptions:function(a){var b=this.chart,c=b.options.plotOptions,
b=b.userOptions||{},d=b.plotOptions||{},e=c[this.type];this.userOptions=a;c=C(e,c.series,a);this.tooltipOptions=C(J.tooltip,J.plotOptions[this.type].tooltip,b.tooltip,d.series&&d.series.tooltip,d[this.type]&&d[this.type].tooltip,a.tooltip);null===e.marker&&delete c.marker;return c},getCyclic:function(a,b,c){var d=this.userOptions,e="_"+a+"Index",f=a+"Counter";b||(u(d[e])?b=d[e]:(d[e]=b=this.chart[f]%c.length,this.chart[f]+=1),b=c[b]);this[a]=b},getColor:function(){this.options.colorByPoint||this.getCyclic("color",
this.options.color||oa[this.type].color,this.chart.options.colors)},getSymbol:function(){var a=this.options.marker;this.getCyclic("symbol",a.symbol,this.chart.options.symbols);/^url/.test(this.symbol)&&(a.radius=0)},drawLegendSymbol:ub.drawLineMarker,setData:function(a,b,c,d){var e=this,f=e.points,g=f&&f.length||0,h,k=e.options,l=e.chart,m=null,n=e.xAxis,q=n&&!!n.categories,p=e.tooltipPoints,t=k.turboThreshold,u=this.xData,w=this.yData,x=(h=e.pointArrayMap)&&h.length;a=a||[];h=a.length;b=r(b,!0);
if(!1===d||!h||g!==h||e.cropped||e.hasGroupedData){e.xIncrement=null;e.pointRange=q?1:k.pointRange;e.colorCounter=0;s(this.parallelArrays,function(a){e[a+"Data"].length=0});if(t&&h>t){for(c=0;null===m&&c<h;)m=a[c],c++;if(ba(m)){q=r(k.pointStart,0);k=r(k.pointInterval,1);for(c=0;c<h;c++)u[c]=q,w[c]=a[c],q+=k;e.xIncrement=q}else if(xa(m))if(x)for(c=0;c<h;c++)k=a[c],u[c]=k[0],w[c]=k.slice(1,x+1);else for(c=0;c<h;c++)k=a[c],u[c]=k[0],w[c]=k[1];else U(12)}else for(c=0;c<h;c++)a[c]!==v&&(k={series:e},e.pointClass.prototype.applyOptions.apply(k,
[a[c]]),e.updateParallelArrays(k,c),q&&k.name&&(n.names[k.x]=k.name));ga(w[0])&&U(14,!0);e.data=[];e.options.data=a;for(c=g;c--;)f[c]&&f[c].destroy&&f[c].destroy();p&&(p.length=0);n&&(n.minRange=n.userMinRange);e.isDirty=e.isDirtyData=l.isDirtyBox=!0;c=!1}else s(a,function(a,b){f[b].update(a,!1,null,!1)});b&&l.redraw(c)},processData:function(a){var b=this.xData,c=this.yData,d=b.length,e;e=0;var f,g,h=this.xAxis,k,l=this.options;k=l.cropThreshold;var m=0,n=this.isCartesian,q,p;if(n&&!this.isDirty&&
!h.isDirty&&!this.yAxis.isDirty&&!a)return!1;h&&(q=h.getExtremes(),p=q.min,q=q.max);if(n&&this.sorted&&(!k||d>k||this.forceCrop))if(b[d-1]<p||b[0]>q)b=[],c=[];else if(b[0]<p||b[d-1]>q)e=this.cropData(this.xData,this.yData,p,q),b=e.xData,c=e.yData,e=e.start,f=!0,m=b.length;for(k=b.length-1;0<=k;k--)d=b[k]-b[k-1],!f&&b[k]>p&&b[k]<q&&m++,0<d&&(g===v||d<g)?g=d:0>d&&this.requireSorting&&U(15);this.cropped=f;this.cropStart=e;this.processedXData=b;this.processedYData=c;this.activePointCount=m;null===l.pointRange&&
(this.pointRange=g||1);this.closestPointRange=g},cropData:function(a,b,c,d){var e=a.length,f=0,g=e,h=r(this.cropShoulder,1),k;for(k=0;k<e;k++)if(a[k]>=c){f=w(0,k-h);break}for(;k<e;k++)if(a[k]>d){g=k+h;break}return{xData:a.slice(f,g),yData:b.slice(f,g),start:f,end:g}},generatePoints:function(){var a=this.options.data,b=this.data,c,d=this.processedXData,e=this.processedYData,f=this.pointClass,g=d.length,h=this.cropStart||0,k,l=this.hasGroupedData,m,n=[],q;b||l||(b=[],b.length=a.length,b=this.data=b);
for(q=0;q<g;q++)k=h+q,l?n[q]=(new f).init(this,[d[q]].concat(ya(e[q]))):(b[k]?m=b[k]:a[k]!==v&&(b[k]=m=(new f).init(this,a[k],d[q])),n[q]=m),n[q].index=k;if(b&&(g!==(c=b.length)||l))for(q=0;q<c;q++)q!==h||l||(q+=g),b[q]&&(b[q].destroyElements(),b[q].plotX=v);this.data=b;this.points=n},getExtremes:function(a){var b=this.yAxis,c=this.processedXData,d,e=[],f=0;d=this.xAxis.getExtremes();var g=d.min,h=d.max,k,l,m,n;a=a||this.stackedYData||this.processedYData;d=a.length;for(n=0;n<d;n++)if(l=c[n],m=a[n],
k=null!==m&&m!==v&&(!b.isLog||m.length||0<m),l=this.getExtremesFromAll||this.cropped||(c[n+1]||l)>=g&&(c[n-1]||l)<=h,k&&l)if(k=m.length)for(;k--;)null!==m[k]&&(e[f++]=m[k]);else e[f++]=m;this.dataMin=r(void 0,ra(e));this.dataMax=r(void 0,ka(e))},translate:function(){this.processedXData||this.processData();this.generatePoints();for(var a=this.options,b=a.stacking,c=this.xAxis,d=c.categories,e=this.yAxis,f=this.points,g=f.length,h=!!this.modifyValue,k=a.pointPlacement,l="between"===k||ba(k),m=a.threshold,
a=0;a<g;a++){var n=f[a],q=n.x,p=n.y,t=n.low,s=b&&e.stacks[(this.negStacks&&p<m?"-":"")+this.stackKey];e.isLog&&0>=p&&(n.y=p=null,U(10));n.plotX=c.translate(q,0,0,0,1,k,"flags"===this.type);b&&this.visible&&s&&s[q]&&(s=s[q],p=s.points[this.index+","+a],t=p[0],p=p[1],0===t&&(t=r(m,e.min)),e.isLog&&0>=t&&(t=null),n.total=n.stackTotal=s.total,n.percentage=s.total&&n.y/s.total*100,n.stackY=p,s.setOffset(this.pointXOffset||0,this.barW||0));n.yBottom=u(t)?e.translate(t,0,1,0,1):null;h&&(p=this.modifyValue(p,
n));n.plotY="number"===typeof p&&Infinity!==p?e.translate(p,0,1,0,1):v;n.clientX=l?c.translate(q,0,0,0,1):n.plotX;n.negative=n.y<(m||0);n.category=d&&d[n.x]!==v?d[n.x]:n.x}this.getSegments()},animate:function(a){var b=this.chart,c=b.renderer,d;d=this.options.animation;var e=this.clipBox||b.clipBox,f=b.inverted,g;d&&!aa(d)&&(d=oa[this.type].animation);g=["_sharedClip",d.duration,d.easing,e.height].join();a?(a=b[g],d=b[g+"m"],a||(b[g]=a=c.clipRect(x(e,{width:0})),b[g+"m"]=d=c.clipRect(-99,f?-b.plotLeft:
-b.plotTop,99,f?b.chartWidth:b.chartHeight)),this.group.clip(a),this.markerGroup.clip(d),this.sharedClipKey=g):((a=b[g])&&a.animate({width:b.plotSizeX},d),b[g+"m"]&&b[g+"m"].animate({width:b.plotSizeX+99},d),this.animate=null)},afterAnimate:function(){var a=this.chart,b=this.sharedClipKey,c=this.group,d=this.clipBox;c&&!1!==this.options.clip&&(b&&d||c.clip(d?a.renderer.clipRect(d):a.clipRect),this.markerGroup.clip());R(this,"afterAnimate");setTimeout(function(){b&&a[b]&&(d||(a[b]=a[b].destroy()),
a[b+"m"]&&(a[b+"m"]=a[b+"m"].destroy()))},100)},drawPoints:function(){var a,b=this.points,c=this.chart,d,e,f,g,h,k,l,m,n=this.options.marker,q=this.pointAttr[""],p,t,s,u=this.markerGroup,w=r(n.enabled,!this.requireSorting||this.activePointCount<.5*this.xAxis.len/n.radius);if(!1!==n.enabled||this._hasPointMarkers)for(f=b.length;f--;)g=b[f],d=K(g.plotX),e=g.plotY,m=g.graphic,p=g.marker||{},t=!!g.marker,a=w&&p.enabled===v||p.enabled,s=c.isInsidePlot(y(d),e,c.inverted),a&&e!==v&&!isNaN(e)&&null!==g.y?
(a=g.pointAttr[g.selected?"select":""]||q,h=a.r,k=r(p.symbol,this.symbol),l=0===k.indexOf("url"),m?m[s?"show":"hide"](!0).animate(x({x:d-h,y:e-h},m.symbolName?{width:2*h,height:2*h}:{})):s&&(0<h||l)&&(g.graphic=c.renderer.symbol(k,d-h,e-h,2*h,2*h,t?p:n).attr(a).add(u))):m&&(g.graphic=m.destroy())},convertAttribs:function(a,b,c,d){var e=this.pointAttrToOptions,f,g,h={};a=a||{};b=b||{};c=c||{};d=d||{};for(f in e)g=e[f],h[f]=r(a[g],b[f],c[f],d[f]);return h},getAttribs:function(){var a=this,b=a.options,
c=oa[a.type].marker?b.marker:b,d=c.states,e=d.hover,f,g=a.color;f={stroke:g,fill:g};var h=a.points||[],k,l=[],m,n=a.pointAttrToOptions;m=a.hasPointSpecificOptions;var q=b.negativeColor,p=c.lineColor,t=c.fillColor;k=b.turboThreshold;var r;b.marker?(e.radius=e.radius||c.radius+e.radiusPlus,e.lineWidth=e.lineWidth||c.lineWidth+e.lineWidthPlus):e.color=e.color||Da(e.color||g).brighten(e.brightness).get();l[""]=a.convertAttribs(c,f);s(["hover","select"],function(b){l[b]=a.convertAttribs(d[b],l[""])});
a.pointAttr=l;g=h.length;if(!k||g<k||m)for(;g--;){k=h[g];(c=k.options&&k.options.marker||k.options)&&!1===c.enabled&&(c.radius=0);k.negative&&q&&(k.color=k.fillColor=q);m=b.colorByPoint||k.color;if(k.options)for(r in n)u(c[n[r]])&&(m=!0);m?(c=c||{},m=[],d=c.states||{},f=d.hover=d.hover||{},b.marker||(f.color=f.color||!k.options.color&&e.color||Da(k.color).brighten(f.brightness||e.brightness).get()),f={color:k.color},t||(f.fillColor=k.color),p||(f.lineColor=k.color),m[""]=a.convertAttribs(x(f,c),l[""]),
m.hover=a.convertAttribs(d.hover,l.hover,m[""]),m.select=a.convertAttribs(d.select,l.select,m[""])):m=l;k.pointAttr=m}},destroy:function(){var a=this,b=a.chart,c=/AppleWebKit\/533/.test(ma),d,e,f=a.data||[],g,h,k;R(a,"destroy");X(a);s(a.axisTypes||[],function(b){if(k=a[b])ha(k.series,a),k.isDirty=k.forceRedraw=!0});a.legendItem&&a.chart.legend.destroyItem(a);for(e=f.length;e--;)(g=f[e])&&g.destroy&&g.destroy();a.points=null;clearTimeout(a.animationTimeout);s("area graph dataLabelsGroup group markerGroup tracker graphNeg areaNeg posClip negClip".split(" "),
function(b){a[b]&&(d=c&&"group"===b?"hide":"destroy",a[b][d]())});b.hoverSeries===a&&(b.hoverSeries=null);ha(b.series,a);for(h in a)delete a[h]},getSegmentPath:function(a){var b=this,c=[],d=b.options.step;s(a,function(e,f){var g=e.plotX,h=e.plotY,k;b.getPointSpline?c.push.apply(c,b.getPointSpline(a,e,f)):(c.push(f?"L":"M"),d&&f&&(k=a[f-1],"right"===d?c.push(k.plotX,h):"center"===d?c.push((k.plotX+g)/2,k.plotY,(k.plotX+g)/2,h):c.push(g,k.plotY)),c.push(e.plotX,e.plotY))});return c},getGraphPath:function(){var a=
this,b=[],c,d=[];s(a.segments,function(e){c=a.getSegmentPath(e);1<e.length?b=b.concat(c):d.push(e[0])});a.singlePoints=d;return a.graphPath=b},drawGraph:function(){var a=this,b=this.options,c=[["graph",b.lineColor||this.color]],d=b.lineWidth,e=b.dashStyle,f="square"!==b.linecap,g=this.getGraphPath(),h=b.negativeColor;h&&c.push(["graphNeg",h]);s(c,function(c,h){var m=c[0],n=a[m];n?(Sa(n),n.animate({d:g})):d&&g.length&&(n={stroke:c[1],"stroke-width":d,fill:"none",zIndex:1},e?n.dashstyle=e:f&&(n["stroke-linecap"]=
n["stroke-linejoin"]="round"),a[m]=a.chart.renderer.path(g).attr(n).add(a.group).shadow(!h&&b.shadow))})},clipNeg:function(){var a=this.options,b=this.chart,c=b.renderer,d=a.negativeColor||a.negativeFillColor,e,f=this.graph,g=this.area,h=this.posClip,k=this.negClip;e=b.chartWidth;var l=b.chartHeight,m=w(e,l),n=this.yAxis;d&&(f||g)&&(d=y(n.toPixels(a.threshold||0,!0)),0>d&&(m-=d),a={x:0,y:0,width:m,height:d},m={x:0,y:d,width:m,height:m},b.inverted&&(a.height=m.y=b.plotWidth-d,c.isVML&&(a={x:b.plotWidth-
d-b.plotLeft,y:0,width:e,height:l},m={x:d+b.plotLeft-e,y:0,width:b.plotLeft+d,height:e})),n.reversed?(b=m,e=a):(b=a,e=m),h?(h.animate(b),k.animate(e)):(this.posClip=h=c.clipRect(b),this.negClip=k=c.clipRect(e),f&&this.graphNeg&&(f.clip(h),this.graphNeg.clip(k)),g&&(g.clip(h),this.areaNeg.clip(k))))},invertGroups:function(){function a(){var a={width:b.yAxis.len,height:b.xAxis.len};s(["group","markerGroup"],function(c){b[c]&&b[c].attr(a).invert()})}var b=this,c=b.chart;b.xAxis&&(Q(c,"resize",a),Q(b,
"destroy",function(){X(c,"resize",a)}),a(),b.invertGroups=a)},plotGroup:function(a,b,c,d,e){var f=this[a],g=!f;g&&(this[a]=f=this.chart.renderer.g(b).attr({visibility:c,zIndex:d||.1}).add(e));f[g?"attr":"animate"](this.getPlotBox());return f},getPlotBox:function(){var a=this.chart,b=this.xAxis,c=this.yAxis;a.inverted&&(b=c,c=this.xAxis);return{translateX:b?b.left:a.plotLeft,translateY:c?c.top:a.plotTop,scaleX:1,scaleY:1}},render:function(){var a=this,b=a.chart,c,d=a.options,e=(c=d.animation)&&!!a.animate&&
b.renderer.isSVG&&r(c.duration,500)||0,f=a.visible?"visible":"hidden",g=d.zIndex,h=a.hasRendered,k=b.seriesGroup;c=a.plotGroup("group","series",f,g,k);a.markerGroup=a.plotGroup("markerGroup","markers",f,g,k);e&&a.animate(!0);a.getAttribs();c.inverted=a.isCartesian?b.inverted:!1;a.drawGraph&&(a.drawGraph(),a.clipNeg());s(a.points,function(a){a.redraw&&a.redraw()});a.drawDataLabels&&a.drawDataLabels();a.visible&&a.drawPoints();a.drawTracker&&!1!==a.options.enableMouseTracking&&a.drawTracker();b.inverted&&
a.invertGroups();!1===d.clip||a.sharedClipKey||h||c.clip(b.clipRect);e&&a.animate();h||(e?a.animationTimeout=setTimeout(function(){a.afterAnimate()},e):a.afterAnimate());a.isDirty=a.isDirtyData=!1;a.hasRendered=!0},redraw:function(){var a=this.chart,b=this.isDirtyData,c=this.group,d=this.xAxis,e=this.yAxis;c&&(a.inverted&&c.attr({width:a.plotWidth,height:a.plotHeight}),c.animate({translateX:r(d&&d.left,a.plotLeft),translateY:r(e&&e.top,a.plotTop)}));this.translate();this.setTooltipPoints&&this.setTooltipPoints(!0);
this.render();b&&R(this,"updatedData")}};var Fb=Ga(pa);na.line=Fb;oa.column=C(Bb,{borderColor:"#FFFFFF",borderRadius:0,groupPadding:.2,marker:null,pointPadding:.1,minPointLength:0,cropThreshold:50,pointRange:null,states:{hover:{brightness:.1,shadow:!1,halo:!1},select:{color:"#C0C0C0",borderColor:"#000000",shadow:!1}},dataLabels:{align:null,verticalAlign:null,y:null},stickyTracking:!1,tooltip:{distance:6},threshold:0});var vb=Ga(pa,{type:"column",pointAttrToOptions:{stroke:"borderColor",fill:"color",
r:"borderRadius"},cropShoulder:0,trackerGroups:["group","dataLabelsGroup"],negStacks:!0,init:function(){pa.prototype.init.apply(this,arguments);var a=this,b=a.chart;b.hasRendered&&s(b.series,function(b){b.type===a.type&&(b.isDirty=!0)})},getColumnMetrics:function(){var a=this,b=a.options,c=a.xAxis,d=a.yAxis,e=c.reversed,f,g={},h,k=0;!1===b.grouping?k=1:s(a.chart.series,function(b){var c=b.options,e=b.yAxis;b.type===a.type&&b.visible&&d.len===e.len&&d.pos===e.pos&&(c.stacking?(f=b.stackKey,g[f]===
v&&(g[f]=k++),h=g[f]):!1!==c.grouping&&(h=k++),b.columnIndex=h)});var c=N(P(c.transA)*(c.ordinalSlope||b.pointRange||c.closestPointRange||c.tickInterval||1),c.len),l=c*b.groupPadding,m=(c-2*l)/k,n=b.pointWidth,b=u(n)?(m-n)/2:m*b.pointPadding,n=r(n,m-2*b);return a.columnMetrics={width:n,offset:b+(l+((e?k-(a.columnIndex||0):a.columnIndex)||0)*m-c/2)*(e?-1:1)}},translate:function(){var a=this,b=a.chart,c=a.options,d=a.borderWidth=r(c.borderWidth,a.activePointCount>.5*a.xAxis.len?0:1),e=a.yAxis,f=a.translatedThreshold=
e.getThreshold(c.threshold),g=r(c.minPointLength,5),h=a.getColumnMetrics(),k=h.width,l=a.barW=w(k,1+2*d),m=a.pointXOffset=h.offset,n=-(d%2?.5:0),q=d%2?.5:1;b.renderer.isVML&&b.inverted&&(q+=1);c.pointPadding&&(l=la(l));pa.prototype.translate.apply(a);s(a.points,function(c){var d=r(c.yBottom,f),h=N(w(-999-d,c.plotY),e.len+999+d),s=c.plotX+m,u=l,v=N(h,d),x;x=w(h,d)-v;P(x)<g&&g&&(x=g,v=y(P(v-f)>g?d-g:f-(e.translate(c.y,0,1,0,1)<=f?g:0)));c.barX=s;c.pointWidth=k;c.tooltipPos=b.inverted?[e.len-h,a.xAxis.len-
s-u/2]:[s+u/2,h+e.pos-b.plotTop];u=y(s+u)+n;s=y(s)+n;u-=s;d=.5>P(v);x=y(v+x)+q;v=y(v)+q;x-=v;d&&(v-=1,x+=1);c.shapeType="rect";c.shapeArgs={x:s,y:v,width:u,height:x}})},getSymbol:pb,drawLegendSymbol:ub.drawRectangle,drawGraph:pb,drawPoints:function(){var a=this,b=this.chart,c=a.options,d=b.renderer,e=c.animationLimit||250,f,g;s(a.points,function(h){var k=h.plotY,l=h.graphic;k===v||isNaN(k)||null===h.y?l&&(h.graphic=l.destroy()):(f=h.shapeArgs,k=u(a.borderWidth)?{"stroke-width":a.borderWidth}:{},g=
h.pointAttr[h.selected?"select":""]||a.pointAttr[""],l?(Sa(l),l.attr(k)[b.pointCount<e?"animate":"attr"](C(f))):h.graphic=d[h.shapeType](f).attr(g).attr(k).add(a.group).shadow(c.shadow,null,c.stacking&&!c.borderRadius))})},animate:function(a){var b=this.yAxis,c=this.options,d=this.chart.inverted,e={};S&&(a?(e.scaleY=.001,a=N(b.pos+b.len,w(b.pos,b.toPixels(c.threshold))),d?e.translateX=a-b.len:e.translateY=a,this.group.attr(e)):(e.scaleY=1,e[d?"translateX":"translateY"]=b.pos,this.group.animate(e,
this.options.animation),this.animate=null))},remove:function(){var a=this,b=a.chart;b.hasRendered&&s(b.series,function(b){b.type===a.type&&(b.isDirty=!0)});pa.prototype.remove.apply(a,arguments)}});na.column=vb;oa.bar=C(oa.column);var Gb=Ga(vb,{type:"bar",inverted:!0});na.bar=Gb;x(T,{Axis:va,Chart:$a,Color:Da,Point:Ta,Tick:ua,Renderer:Ea,Series:pa,SVGElement:M,SVGRenderer:Ea,arrayMin:ra,arrayMax:ka,charts:ea,dateFormat:Ia,format:Ha,pathAnim:bb,getOptions:function(){return J},hasBidiBug:yb,isTouchDevice:nb,
numberFormat:da,seriesTypes:na,setOptions:function(a){J=C(!0,J,a);gb();return J},addEvent:Q,removeEvent:X,createElement:za,discardElement:Ja,css:V,each:s,extend:x,map:rb,merge:C,pick:r,splat:ya,extendClass:Ga,pInt:z,wrap:Ua,svg:S,canvas:$,vml:!S&&!$,product:"Highcharts 4.0.4",version:"/Highstock 2.0.4"})})(); 